### ISSUE TITLE
React Context issue

### ISSUE THREAD

**Issue by MilosJo** [JohannesKlauss/react-hotkeys-hook#1]
Hey there,
I really liked the idea of your API, but I have ran into an issue.
**React version: "16.8.1"**

This is the component where I use it.
`cart` is from my Context and `toggleShowCart` is a method on it, which works just fine.
`"esc"` gets logged to the console when I press it.
```
const Cart = ({ fixed, pinned, cart }) => {
  useHotKeys('esc', () => console.log('esc') || cart.toggleShowCart);
  return (
    <Wrapper
      fixed={fixed}
      pinned={pinned}
    >
      <Overlay isVisible={cart.isOpen} onClick={cart.toggleShowCart} />
      <Base
        fixed={fixed}
        pinned={pinned}
        isOpen={cart.isOpen}
      />
      . . .
```
Regards,
Milos

**Comment by JohannesKlauss** [comment]
Hi Milos,
thanks for reporting the issue, but I am not quite sure what your problem is exactly. `console.log('esc') || cart.toggleShowCart` will always log `esc` to the console since it's a method call. Could you please specify what you expect the behavior should be and what it actually is? Thank you.

**Comment by MilosJo** [comment]
Hey @JohannesKlauss 
Well, it is not invoking my function `toggleShowCart` properly. As name states, it should open/close my cart component, and its functioning properly when I use it like `onClick={cart.toggleShowCart}`
It is not working tho, when I try to bind `esc` key to call this `toggleShowCart` method.

**Comment by JohannesKlauss** [comment]
@MilosJo That is because you are not invoking the function at all:
```js
console.log('esc') || cart.toggleShowCart
```
You have to invoke the function inside the callback, since it is not the callback itself:
```js
useHotKeys('esc', () => console.log('esc') || cart.toggleShowCart());
```

**Comment by MilosJo** [comment]
@JohannesKlauss 
Sadly, I have tried that solution too, and it did not work :(

**Comment by JohannesKlauss** [comment]
Can you please provide a working codebox or pen example, where this issue is reproduced? Since the `console.log('esc')` is executed, the callback itself gets executed properly. Currently I don't see how this could be related to the hook, but a codebox example could deliver some answers.

**Comment by MilosJo** [comment]
Hey @JohannesKlauss 
I tried it on `creat-react-app`, and copied most of the code and it worked like charm.
Anyways, I had deadline so I go with custom solution.
Thanks, your help is greatly appreciated.
