### ISSUE TITLE
Stale state

### ISSUE THREAD

**Issue by MishaFrenkman** [JohannesKlauss/react-hotkeys-hook#101]
Following code behaves unexpectedly.
Prints initial value and not updated state value;

```javascript
import React, {useState, useEffect} from 'react';
import { useHotkeys } from 'react-hotkeys-hook';

function Component() {
  const [test, setTest] = useState(0);
  useEffect(() => {
    setTest(1);
  }, []);
  useHotkeys('a', () => console.log(test));

  return <p>{test}</p>
}

export default Component
```

**Comment by JohannesKlauss** [comment]
@MishaFrenkman thank you very much for your bug report. This issue got fixed with #99. I published a new version (1.4.0). If you update the package the issue will be gone.

**Comment by amanharwara** [comment]
Does this not work with the context API? The state is stale when using the Context API.
Here is example code where it doesn't work:

```tsx
const Component = () => {
	const {state, setState} = useContext(context);
	
	useEffect(()=>{
		setState({
			example: 1
		});
	});

	useHotkeys('ctrl+a', ()=>{
		console.log(state);
	});

	return (<div></div>);
}
```

Is there something I'm doing wrong or does it not support the Context API?

**Comment by JohannesKlauss** [comment]
I really don't know how your context is working, where it is wrapped. Also your `useEffect` does not specify a dep array.

**Comment by amanharwara** [comment]
Turns out adding the context value to the `useHotkeys` dep array fixed it. Thanks.

**Comment by KalpeshPopat** [comment]
This bug has resurfaced, i am using v2.1.3 and events fired via shortcut keys are unable to read the state.

**Comment by JohannesKlauss** [comment]
Are you using the deps array of the `useHotkeys array`? Otherwise you will always get stale state. The handler is memoised and has to update itself depending on the values you give it.

**Comment by KalpeshPopat** [comment]
Thanks for the response, i will respond on other thread.
