### ISSUE TITLE
[BUG] "Shifted" keys (e.g. '@', '!', '+') are hard to work with

### ISSUE THREAD

**Issue by alpinagyok** [JohannesKlauss/react-hotkeys-hook#1019]
**Describe the bug**
This is not really a bug, more of an inconvenience but I want to have some discussion on what to do with this problem. An example with `+`:

**To Reproduce**
1. Use `+` as your hotkey -> callback is not triggered

**Expected behavior**
`useHotkeys` works with `+` key.

**Workaround**
`useHotkeys('shift.+', () => {}, { combinationKey: '.' })`. To type `+` (en-US, mac) I have to hold `shift` and press `=`. But the resulted `+` doesn't really have to do anything with `shift`. I assume there are other combinations of "modifier key + key A = key B" that will give the same problem. Maybe it should be possible to have an option to ignore modifiers for specific keys?

**Comment by JohannesKlauss** [comment]
There is exactly that option, you can use the `ignoreModifiers` flag to do so.
