### ISSUE TITLE
Does it makes sense to export more internal types?

### ISSUE THREAD

**Issue by LuanScudeler** [JohannesKlauss/react-hotkeys-hook#1034]
When creating a custom hook on top of `useHotkeys` or typing `useCallback` params I was expecting to be able to import more internal types from the lib as a reliable way to ensure type safety in this situations. 

Currently I see that only `Options` is exported. Would it make sense to export more internal types for usage in these cases? Here is an example of what I've described: https://codesandbox.io/s/magical-clarke-oqjbe7?file=/src/App.tsx:177-368

**Comment by JohannesKlauss** [comment]
Sure, we can certainly do that. What types do you need?

**Comment by LuanScudeler** [comment]
@JohannesKlauss I was able to import internal types from `"react-hotkeys-hook/dist/types"`, but I guess it's still a good thing to have access to them in the main import.

The types to add would be `Keys` and `HotkeyCallback`

**Comment by JohannesKlauss** [comment]
Would you care to open a PR for this?

**Comment by LuanScudeler** [comment]
Sure, I'll do that!

**Comment by JohannesKlauss** [comment]
Released in 4.4.1
