### ISSUE TITLE
Add 'mod' modificator to the official doc

### ISSUE THREAD

**Issue by JuanmaMenendez** [JohannesKlauss/react-hotkeys-hook#1041]
**Is your feature request related to a problem? Please describe.**
I need to handle 'ctrl+c' and 'meta+c' shortcuts to support MacOS and Windows.

The library already includes the 'mod' modificator to handle both cases, however it's not included on the offcial doc
```
// bind cmd/ctrl + c shortcut
useHotkeys('mod+c', handleShortcut);
```

**Describe the solution you'd like**
Add 'mod' reference in the 'Modifiers & Special keys' section
https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/basic-usage#modifiers--special-keys

**Comment by JohannesKlauss** [comment]
Updated the docs accordingly.
