### ISSUE TITLE
[BUG] Unclear mention of filterPreventDefault in the documentation

### ISSUE THREAD

**Issue by krsilas** [JohannesKlauss/react-hotkeys-hook#1042]
**Describe the bug**
The docs reference the options `filterPreventDefault` and `filter` even though they do not exist.
Is this a deprecated feature or do I misunderstand the docs?

**To Reproduce**
1. Go to https://react-hotkeys-hook.vercel.app/docs/api/use-hotkeys#filterpreventdefault
2. Try to use it on the latest version.

Please try and add a codesandbox or stackblitz to reproduce the bug:
https://stackblitz.com/edit/react-ts-jz9ryh?file=App.tsx

**Expected behavior**
Docs reflect the possible properties for the options.

**Additional context**
I can help update the docs. I'm just very new to react-hotkeys-hook and I'm not sure what the expected behavior is.

**Comment by JohannesKlauss** [comment]
Oh, you are absolutely right, those options don't exist anymore. The new options are `enabled` and `preventDefault`

**Comment by JohannesKlauss** [comment]
Updated the docs accordingly
