### ISSUE TITLE
[V5] Remove references to keyCode

### ISSUE THREAD

**Issue by JohannesKlauss** [JohannesKlauss/react-hotkeys-hook#1044]
The `useHotkeys` hook should not bother with the keyCode. Also the store of pressed down keys should not save keyCodes, but only keys.

This is a Breaking Change

- [ ] Remove keyCode references
- [ ] Update docs
- [ ] Remove Tests that listen to keyCodes
- [ ] Document Breaking change

Open Questions:
* How are we going to migrate hotkeys that are listening to combinations like `mod+s`, `shift+1`, etc.?
* For example alt/option+ any character produces wildly different results depending on the keyboard layout. So listening to something like `alt+s` has to be possible without knowing what key it produces.

I see three options for migration:
* Adding a second hook called `useHotkeysCode` or something similar
* Adding a flag to the current key
* "Smartly" decide when to listen for keyCode and when not. I.e. `alt+s` most likely intents to listen for keyCodes, while `/` wants to listen for the produced key.

**Comment by jLynx** [comment]
First off, great project!
Just wanted to see how progress is going on V5? I currently have an issue on V4 where it looks to be using .keyCode rather than .key, so because I have a remapped keyboard, it picks up the incorrect key. It looks like V5 will solve this issue.

**Comment by JohannesKlauss** [comment]
Yes, I am swamped with work currently, so there is very little progress. I hopefully have time in december, but no promises.
