### ISSUE TITLE
[BUG] keyup doesn't get fired for combinations

### ISSUE THREAD

**Issue by moklick** [JohannesKlauss/react-hotkeys-hook#1063]
**Describe the bug**

When I use a combination like "Control+d", keyup doesn't get fired.

**To Reproduce**

This should log "keydown" and "keyup" but it only logs "keydown"

```js 
useHotkeys(["Control+d"],
  (event) => console.log(event.type), {
    keyup: true,
    keydown: true
  });
```

Please try and add a codesandbox or stackblitz to reproduce the bug:
https://codesandbox.io/s/zen-mcclintock-zn44ql?file=/src/App.js:105-212

**Expected behavior**
keyup should get triggered

**Comment by JohannesKlauss** [comment]
You have to use `ctrl` not `Control`
