### ISSUE TITLE
[BUG] `mod` matches both `command` and `control` modifier key on Mac OS

### ISSUE THREAD

**Issue by lukebowerman** [JohannesKlauss/react-hotkeys-hook#1069]
**Describe the bug**
Using the key combo of `mod+e` (or really any single character) is expected to only match `command+e` on a Mac. Unexpectedly it also matches `control+e`

**To Reproduce**
1. Create a shortcut with `mod+e` as the shortcut string
2. On Mac OS try `command+e` ✅ (works as-expcted)
3. On Mac OS try `control+e`  💥 (shortcut should have been ignored)

Repro instance: https://codesandbox.io/s/reverent-christian-qsj6w9

**Expected behavior**
Only `command+e` should match on Mac (per documentation at https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/basic-usage#modifiers--special-keys)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome 115, Firefox 116 & Safari 16.5

**Comment by lukebowerman** [comment]
Appears to behave consistently in all 4.x versions of the library so perhaps this is a mis-understanding of the intended behavior on my part?

**Comment by eportet** [comment]
Having the same issue

**Comment by cm-dyoshikawa** [comment]
On Mac, if we wanted to set just `command`  key excluded `control` key the event, we could use `meta` .

https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/basic-usage#modifiers--special-keys

> The meta key is the same as cmd on macOS and os key on Windows.

**Comment by JohannesKlauss** [comment]
Using `meta` is the correct way.

**Comment by OahMada** [comment]
According to [doc](https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/basic-usage#modifiers--special-keys), this behavior shouldn't happen, or the doc is outdated?
