### ISSUE TITLE
Call ignoreEventWhen only if KeyboardEvent matches a hotkey 

### ISSUE THREAD

**Issue by LuanScudeler** [JohannesKlauss/react-hotkeys-hook#1090]
I would expect `ignoreEventWhen` to be called only if KeyboardEvent matches a hotkey, instead it's being called on every KeyboardEvent.

My opinion is if it's not needed to run on every event it would be more prudent in terms of performance to have it only for hotkey matches, since in an app you end up with a lot of event listeners from `useHotkeys` and if for some reason the user runs something slightly expensive inside the `ignoreEventWhen` callback, it might not be ideal to have it executing on every key press for every listener that is enabled.

Is there a particular reason to do this for every event or could we call it only for hotkey matches?

**Comment by JohannesKlauss** [comment]
I don't see a reason why it should be called every time. I would very much welcome a PR for that 🙂

**Comment by JohannesKlauss** [comment]
Released in 4.4.3
