### ISSUE TITLE
[BUG] 4.4.2 missing dist

### ISSUE THREAD

**Issue by arvinxx** [JohannesKlauss/react-hotkeys-hook#1109]
**Describe the bug**

please ref to https://www.npmjs.com/package/react-hotkeys-hook?activeTab=code

version 4.4.2 missing dist

<img width="826" alt="image" src="https://github.com/JohannesKlauss/react-hotkeys-hook/assets/28616219/e3f85917-6562-4140-b9d6-2e7c4b9d86ec">

**Comment by JohannesKlauss** [comment]
Yes, this was by mistake. Please use 4.4.3
