### ISSUE TITLE
[BUG] `option` Key No Longer Registers in v4?

### ISSUE THREAD

**Issue by benshope** [JohannesKlauss/react-hotkeys-hook#1119]
**Describe the bug**
The word `option` (as in `option+a`) no longer works for mac key commands after upgrading to v4. It seems the hokey must be `alt` (as in `alt+a`) to work on mac. This may be intentional but I'm not seeing it in the docs.

**To Reproduce**
1. Go to [this codepen](https://codesandbox.io/p/devbox/elated-keldysh-zjtmsm?file=%2Fapp%2Fpage.tsx%3A7%2C6&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr8hmjvy00083b87uebn72a7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr8hmjvy00033b87xnkg1iir%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr8hmjvy00053b87t8mmu32o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr8hmjvy00073b870x2fgb9x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr8hmjvy00033b87xnkg1iir%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr8hmjvy00023b87q8qipen4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A6%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A6%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr8hmjvy00033b87xnkg1iir%2522%252C%2522activeTabId%2522%253A%2522clr8hmjvy00023b87q8qipen4%2522%257D%252C%2522clr8hmjvy00073b870x2fgb9x%2522%253A%257B%2522id%2522%253A%2522clr8hmjvy00073b870x2fgb9x%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr8hmjvy00063b87h09ppqwm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr8hmjvy00063b87h09ppqwm%2522%257D%252C%2522clr8hmjvy00053b87t8mmu32o%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr8hmjvy00043b87i5nskwyy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clr8hmjvy00053b87t8mmu32o%2522%252C%2522activeTabId%2522%253A%2522clr8hmjvy00043b87i5nskwyy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
2. Press the `option+b`
3. The alert does not fire

Please try and add a codesandbox or stackblitz to reproduce the bug:
[Codepen](https://codesandbox.io/p/devbox/elated-keldysh-zjtmsm?file=%2Fapp%2Fpage.tsx%3A7%2C6&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr8hmjvy00083b87uebn72a7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr8hmjvy00033b87xnkg1iir%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr8hmjvy00053b87t8mmu32o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr8hmjvy00073b870x2fgb9x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr8hmjvy00033b87xnkg1iir%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr8hmjvy00023b87q8qipen4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A6%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A6%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr8hmjvy00033b87xnkg1iir%2522%252C%2522activeTabId%2522%253A%2522clr8hmjvy00023b87q8qipen4%2522%257D%252C%2522clr8hmjvy00073b870x2fgb9x%2522%253A%257B%2522id%2522%253A%2522clr8hmjvy00073b870x2fgb9x%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr8hmjvy00063b87h09ppqwm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr8hmjvy00063b87h09ppqwm%2522%257D%252C%2522clr8hmjvy00053b87t8mmu32o%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr8hmjvy00043b87i5nskwyy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clr8hmjvy00053b87t8mmu32o%2522%252C%2522activeTabId%2522%253A%2522clr8hmjvy00043b87i5nskwyy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Expected behavior**
I expected the hotkey to register for `option+b`

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 4.4.3

**Additional context**
n/a

**Comment by JohannesKlauss** [comment]
It's referred to in the info box here: https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/basic-usage#multiple-hotkeys

So this is intentional in effort to reduce friction between different os environments.

**Comment by benshope** [comment]
@JohannesKlauss thanks for the quick response - the docs say 
> Since version 4 `alt` and `option` are identical

when it might be more accurate to say 
> Since version 4 `option` is deprecated in favor of `alt`.  `option` no longer triggers hotkeys
