### ISSUE TITLE
What is v4.5.0?

### ISSUE THREAD

**Issue by willmanduffy** [JohannesKlauss/react-hotkeys-hook#1130]
**Describe the bug**
Looking at npm I see there's a [v4.5.0 release](https://www.npmjs.com/package/react-hotkeys-hook), however there is no code changes or releases in this repo that describe a v4.5.0. Everything here is still v4.4.4. Is this a mistaken npm release?

**Comment by JohannesKlauss** [comment]
See https://github.com/JohannesKlauss/react-hotkeys-hook/releases/tag/v4.5.0
