### ISSUE TITLE
[BUG] Working locally, but not in production

### ISSUE THREAD

**Issue by mnapoli** [JohannesKlauss/react-hotkeys-hook#1131]
**Describe the bug**

Hotkeys work perfectly locally, but not in production.

Note that some hotkeys are working (`?`), but 2 are to (`+` and `-`) and I cannot explain why!

**To Reproduce**

```
    useHotkeys('-', () => {
        setTimeSize(timeSize * 2);
    },);
```

**Expected behavior**
It works locally (local development) and in production (deployed to Netlify).

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome

**Comment by JohannesKlauss** [comment]
Please prodvice a reproducible

**Comment by mnapoli** [comment]
😅 sure: https://watch-aws-lambda-scale.com/

Click "Send request" multiple times, then try the `+/-` shortcuts. The animation should zoom in/out. Works perfectly locally. Now this is deployed to netlify. Note that the `?` should work, which is weird!

**Comment by JohannesKlauss** [comment]
This is not a reproducible. This is your deployed app. Please provide a reproducible code sandbox

**Comment by JohannesKlauss** [comment]
But looking into the shipped code of your page I can already tell that this is not an issue with the library. You are not shipping any javascript to the client that would relate to the usage of this hook.

**Comment by mnapoli** [comment]
> You are not shipping any javascript to the client that would relate to the usage of this hook.

What do you mean? Do you mean that the shipped code does not use your library? I think a simple way to check that it's the case is to try the `?` shortcut: this one works. So the library is indeed shipped to the client, and is executed.

I understand your position though, any shortcut to close the issue and ignore is fair, I'm an OSS maintainer of 15 years too, I know the tricks 🤷

Anyway, this is a long shot because you might have no time to provide support at all, but: if you have any remote idea on why this could be happening, that could put me on the right track to debug, feel free to share. Thank you.

**Comment by JohannesKlauss** [comment]
As I said, please provide a reproducible sandbox.

**Comment by kubk** [comment]
For those who may encounter it in the future, in my case the reason for the issue turned out to be a Chrome extension (specifically Vimium) that overrides some of the hotkeys. Turning it off for my website solved the issue. Sorry for bringing up the old thread. I just had exactly the same issue (some of the hotkeys didn’t work in production) and initially mistakenly attributed it to the library.
