### ISSUE TITLE
Several entries in mappedKeys look suspicious

### ISSUE THREAD

**Issue by frouaix** [JohannesKlauss/react-hotkeys-hook#1153]
https://github.com/JohannesKlauss/react-hotkeys-hook/blob/fe079b9cbd712f9eb3814fcaf344dc8f660b9bd8/src/parseHotkeys.ts#L5

‘-‘ maps to slash?
‘#’ maps to backslash?
‘+’ maps to bracketright?

In my app (sorry, no standalone repro)
‘alt+-‘ does not trigger as expected on a US qwerty keyboard, ‘alt+minus’ does.

**Comment by JohannesKlauss** [comment]
Yes, this is a known issue which will be fixed in 5.0.0
Until then you can use the pre release version [5.0.0-1](https://www.npmjs.com/package/react-hotkeys-hook/v/5.0.0-1)

**Comment by frouaix** [comment]
Ok - I had a quick look at the new version. I don’t understand how Ctrl-Z can be correctly recognized on a US qwerty keyboard as well as a FR azerty keyboard, but that’s another issue.
