### ISSUE TITLE
[BUG] preventDefault seems not work when use `command + s `

### ISSUE THREAD

**Issue by LeeeeeeM** [JohannesKlauss/react-hotkeys-hook#1154]
**Describe the bug**
preventDefault seems not work when use `command + s `

**To Reproduce**
Just click `command + s`， it does't work in ^4.5.1 with react v18+,
but it works well in 1.5.3 with react v16.8.

Please try and add a codesandbox or stackblitz to reproduce the bug:
https://stackblitz.com/edit/react-bn1xfi?file=src%2FApp.js

**Expected behavior**

**Screenshots**
![image](https://github.com/JohannesKlauss/react-hotkeys-hook/assets/35845083/b881e810-5fd2-4aa8-bb78-d01f416d3cca)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  mac 14.2.1 
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 121.0.6167.160

**Additional context**

**Comment by LeeeeeeM** [comment]
Maybe `command` should convert to `meta`

**Comment by JohannesKlauss** [comment]
`command` is not a valid key. Use `meta` instead.
