### ISSUE TITLE
[BUG] Why is # key mapped to Backslash

### ISSUE THREAD

**Issue by limoncellooooo** [JohannesKlauss/react-hotkeys-hook#1155]
**Describe the bug**

The # key is mapped to backslash
https://github.com/JohannesKlauss/react-hotkeys-hook/blob/fe079b9cbd712f9eb3814fcaf344dc8f660b9bd8/src/parseHotkeys.ts#L13C3-L13C20

Would it be possible to customize this mapping?

**To Reproduce**

**Expected behavior**
I don't want this custom mapping

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by JohannesKlauss** [comment]
Have a look at this comment
https://github.com/JohannesKlauss/react-hotkeys-hook/issues/1153#issuecomment-1993822889
