### ISSUE TITLE
[BUG] hotKeys trigger from input inside WebComponent

### ISSUE THREAD

**Issue by HJK181** [JohannesKlauss/react-hotkeys-hook#1161]
**Describe the bug**
Hotkeys triggers if users has focus on an input inside a WebComponent. This is because events that happen in shadow DOM have the host element as the target, when caught outside of the component, see: https://javascript.info/shadow-dom-events

**To Reproduce**
1. Render a WebComponent input inside your React component, e.g. https://www.webcomponents.org/element/@polymer/paper-input
2. Use the useHotkeys with some keys
3. Focus the WebComponent input and press a key triggering the hotKey

Please try and add a [codesandbox](https://codesandbox.io/p/sandbox/funny-pond-d2mr7k?file=%2Fsrc%2FApp.js%3A10%2C2&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clul7k2i900062v6llgbfnte3%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clul7k2i900022v6lo86acdwc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clul7k2i900032v6l0v3gusat%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clul7k2i900052v6ljtbjuh35%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B48.40603866122574%252C51.59396133877426%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clul7k2i900022v6lo86acdwc%2522%253A%257B%2522id%2522%253A%2522clul7k2i900022v6lo86acdwc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clul7lewi005d2v6lpoxor6pp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A2%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clul7lewi005d2v6lpoxor6pp%2522%257D%252C%2522clul7k2i900052v6ljtbjuh35%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clul7k2i900042v6l8vtyezn0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clul7k2i900052v6ljtbjuh35%2522%252C%2522activeTabId%2522%253A%2522clul7k2i900042v6l8vtyezn0%2522%257D%252C%2522clul7k2i900032v6l0v3gusat%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clul7k2i900032v6l0v3gusat%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) reproduce the bug: 

just press c while focus is inside the input.

**Expected behavior**
The hotkey is not triggered if the focus element is one of the elements the hook already takes care of when used inside a WebComponent. To solve this, `isHotkeyEnabledOnTag` should not just use `_ref.target` but also check if the `_ref.composedPath()[0].tagName` if the `composed` property of the event is `true`, indicating that the event is a composed event that can pass through shadow DOM boundaries, including events from within web components.

**Comment by HJK181** [comment]
I gave it a try: https://github.com/JohannesKlauss/react-hotkeys-hook/pull/1164

**Comment by JohannesKlauss** [comment]
Thank you for your work, I'll have a look at it.

**Comment by JohannesKlauss** [comment]
Finally merged in 4.6.1.
Thank you for your work!
