### ISSUE TITLE
[BUG] don't trigger hot keys when input focus

### ISSUE THREAD

**Issue by luke358** [JohannesKlauss/react-hotkeys-hook#1177]
**Describe the bug**
don't trigger hot keys when input focus

**To Reproduce**
1. Go to 'focus input'
2. Click on 'esc'
3. see console

Please try and add a codesandbox or stackblitz to reproduce the bug:
<-- Link to reproducable -->
[codesandbox](https://codesandbox.io/p/sandbox/hot-keys-54sfkq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwelcqb800063b6m9hyu1igx%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwelcqb800023b6mrev0u636%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwelcqb800033b6mshggojpy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwelcqb800053b6mlvco3vo8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwelcqb800023b6mrev0u636%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwelcqb800013b6m871zih7p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clwelcqb800023b6mrev0u636%2522%252C%2522activeTabId%2522%253A%2522clwelcqb800013b6m871zih7p%2522%257D%252C%2522clwelcqb800053b6mlvco3vo8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwelcqb800043b6mm7ennfkq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwelcqb800053b6mlvco3vo8%2522%252C%2522activeTabId%2522%253A%2522clwelcqb800043b6mm7ennfkq%2522%257D%252C%2522clwelcqb800033b6mshggojpy%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwelcqb800033b6mshggojpy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
**Expected behavior**
trigger hot keys

**Comment by JohannesKlauss** [comment]
Please consult the documentation, there is an option to disable this behavior
