### ISSUE TITLE
Question : Callback is being executed infinitely

### ISSUE THREAD

**Issue by WinterCore** [JohannesKlauss/react-hotkeys-hook#118]
Hi, this is more of a question than an issue.
I'm having this weird issue where the callback for ```useHotkeys``` is being executed endlessly even though the button is only pressed once.
[Example](https://codesandbox.io/s/vigorous-maxwell-szket) Try to press the space key.

Shouldn't the callback be called only once (if the button got pressed once), regardless of what's going on in the component ? 
I'm pretty sure I'm missing something here, but I'm not sure what it is.

Edit : This only happens when you update multiple state variables in the callback

Thanks in advance.

**Comment by JohannesKlauss** [comment]
Hi @WinterCore 
thanks for reporting the issue. I'll look into it.

**Comment by WinterCore** [comment]
Hi
After some digging I found where the issue lies.
Hotkeys.js stores event handlers in an array of objects, and when you unbind something it just makes the object for that handler empty but doesn't actually remove it.
Example image :
![Annotation 2019-07-21 110507](https://user-images.githubusercontent.com/8643036/61589242-7443cf80-aba7-11e9-88c6-bd502554cef5.jpg)


So what's happening is that when the first event fires hotkeys.js gets that array of event handlers, filters it to get rid of empty objects and executes the rest. when it executes a callback the component has to rerender (Because the callback is changing the component's state), when the component starts rerendering the old event handler gets cleared in your code ```hotkeys.unbind``` and a new event handler is associated with the key. meanwhile we're still in the ```for``` loop which is still executing all the callbacks for that specific key (event).
So the component finished rendering and we have a new item in the event handlers array. so now the code flow goes back to the for loop, so now we have a new handler in the event handlers array, so the for loop ends up executing the event handler again, even though the key was not pressed, the component rerenders, attaches another event, etc. and this keeps going on forever. See image below.
![Capture](https://user-images.githubusercontent.com/8643036/61589386-62fbc280-aba9-11e9-8890-a8c9e5c5856f.JPG)

I ended up working around the issue by using ```useCallback``` on the handler.
![fasdf](https://user-images.githubusercontent.com/8643036/61589396-91799d80-aba9-11e9-904c-661e81d5746d.JPG)

This works for now, but if you actually want a different handler on every render, this is where the issue arises.
I'm not sure if this should be reported to hotkeys.js, and even if it was reported, I don't think there's anything to be done or not worth the effort at least.

**Comment by JohannesKlauss** [comment]
@WinterCore This is a problem with the package currently handling the callback. Right now you have to memoise the callback yourself since I don't know how I could memoise it inside the hook with knowing about all dependencies. I should add this to the docs.

To prevent the infinite loop change the callback to this:

`useHotkeys("space", React.useCallback(() => {
  console.log('fired');

  setFoo(foo => {
    setBar(!foo);
      
    return !foo;
  });
}, [setFoo]));`

**Comment by JohannesKlauss** [comment]
@WinterCore With the release of 1.5.0 the callback gets memoised inside the hotkeys hook. So you don't have to do it yourself anymore.
Check out this section of the docs: https://johannesklauss.github.io/react-hotkeys-hook/docs-use-hotkeys#memoisation
