### ISSUE TITLE
[BUG] `mod` modifier listens to `ctrl` on macOS 

### ISSUE THREAD

**Issue by ItaiYosephi** [JohannesKlauss/react-hotkeys-hook#1181]
**Describe the bug**
`mod` should only listen to `meta`, but on macOS, it also listens to `ctrl`.
 

**To Reproduce**
1. using macOS, press `ctrl+k` in the following stackblitz demo

[Link to reproducable](https://stackblitz.com/edit/vitejs-vite-ug7fn5?file=package.json,src%2Fmain.tsx,src%2FApp.tsx,src%2Findex.css)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome

**Comment by JohannesKlauss** [comment]
This is not a bug, but standard behavior and mentioned in the docs. If you want to listen to `meta`, then you have to listen to `meta` and not `mod`. `mod` will capture both modifier keys. This is the browsers behavior

**Comment by ItaiYosephi** [comment]
@JohannesKlauss as @terryttsai commented, from the docs its seems that `mod` shuld only correspond to `cmd` on mac... 
Maybe we can reopen this as a feature request? To add a new modifier that will correspond to ctrl on windows and cmd on mac?
Currently there is now way to achieve it, but it seems like a pretty common use case . For example, only `cmd+k` opens a command menu on GitHub/Linear/Jira on mac (`ctrl+k` opens the menu on windows but not on mac).
