### ISSUE TITLE
[BUG] `+` / Plus key not registering

### ISSUE THREAD

**Issue by KieranTH** [JohannesKlauss/react-hotkeys-hook#1186]
**Describe the bug**
Any combination including a `plus` does not fire. This also happens when the combination key is changed to something other than `plus` to make sure there is no conflict from the string parsing.

**To Reproduce**
1. Go to https://codesandbox.io/p/sandbox/pedantic-goldberg-9tv8xd
2. Attempt to use `"alt.+"` as combination
3. Fails to register

**Expected behavior**
The hotkey should be triggered when a plus is included, a general usage for this is additional/additive actions, such as `alt` and `+` to increase a number etc.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Chrome + FireFox tested
 - Version: 4.5.0

**Comment by JohannesKlauss** [comment]
You have to change your `splitKey` (which is `+` by default) to listen to that key: https://react-hotkeys-hook.vercel.app/docs/api/use-hotkeys#splitkey

**Comment by KieranTH** [comment]
Great thank you!
