### ISSUE TITLE
Some shift modifiers not working in v5

### ISSUE THREAD

**Issue by stinoga** [JohannesKlauss/react-hotkeys-hook#1211]
**Describe the bug**
The following key combinations aren't working in v5.0.0-1:
"shift+["
"shift+]"
"shift+,"
"shift+."

Comma hotkey seems broken as well: ","

Please try and add a codesandbox or stackblitz to reproduce the bug:
https://codesandbox.io/p/sandbox/rhd3fp

**Expected behavior**
Callbacks should be initiated.

**Desktop (please complete the following information):**
 - OS: [macOS Sonoma]
 - Browser [chrome]
 - Version [5.0.0-1]

**Comment by JohannesKlauss** [comment]
You would listen to all of these with

```ts
useHotkeys('[', callback, {useKey: true})
```

Listening to comma:

```ts
useHotkeys(',', callback, {delimiter: '.'})
useHotkeys('shift+,', callback, {delimiter: '.'})
```

**Comment by stinoga** [comment]
Thanks! Closing this out.
