### ISSUE TITLE
[BUG] search bar in documentation can't take any input

### ISSUE THREAD

**Issue by RealmX1** [JohannesKlauss/react-hotkeys-hook#1215]
can't be pasted into nor accept direct keyboard input.
![image](https://github.com/user-attachments/assets/382d5473-3f08-44d5-b8c2-9844c96a9ed6)

https://react-hotkeys-hook.vercel.app/

Happens when I have large amount of tabs (~400) opened in chrome).

I've recently found a lot of issues on many websites when running chrome with this many tabs open... I don't think it is hard resource constraint issue, as usage of cpu/ram/gpu are all low.

**Comment by JohannesKlauss** [comment]
If you found a lot of issues on many websites when running chrome with a lot of tabs open it sounds like a chrome bug.
