### ISSUE TITLE
Add documentation for how to build locally and develop

### ISSUE THREAD

**Issue by aleccool213** [JohannesKlauss/react-hotkeys-hook#139]
Trying to build and `npm link` this locally to fix an issue and it is not straightforward.

**Comment by JohannesKlauss** [comment]
Basically you can use `docz:dev` and use the docz playground to develop locally. But yeah, I will add some documentation for this.

**Comment by JohannesKlauss** [comment]
I added a section in the readme: https://github.com/JohannesKlauss/react-hotkeys-hook#local-development
