### ISSUE TITLE
Duplicate hotkey usages interfere with each other

### ISSUE THREAD

**Issue by godspeedelbow** [JohannesKlauss/react-hotkeys-hook#153]
I have two components, mounted simultaneously, that both register the same hotkey:

```js
useHotkeys(
  "ctrl+f",
  useCallback(onOpen, [])
);
```

Whenever one of them gets unmounted, the hotkey stops working for the other component as well.

I think it's because of this line:
https://github.com/JohannesKlauss/react-hotkeys-hook/blob/11e6ccec57498e9a3c99f43f4797c2a06d57cbbf/src/index.ts#L12

Because when I change it to:
```js
return () => hotkeys.unbind(keys, memoisedCallback);
```

it works as expected.

**Comment by JohannesKlauss** [comment]
Thank you very much for the bug report. Would you mind to create a PR with the change?

**Comment by godspeedelbow** [comment]
https://github.com/JohannesKlauss/react-hotkeys-hook/pull/154

👍
