### ISSUE TITLE
Statically type 'keys' argument

### ISSUE THREAD

**Issue by CodingDive** [JohannesKlauss/react-hotkeys-hook#156]
Hey, thank you so much for this library. I was about to create my own module when I found your library which closely resembled what I had in mind. 😍 	

Is it possible to add static types to the keys argument? I always look up the event key names [here](https://keycode.info/) and I'd much rather be using intellisense if possible.

**Comment by JohannesKlauss** [comment]
Hmh... I am not quite sure.
It's easy to statically type the basic keys, alphanumeric + modifiers.
But you can also do something like `ctrl+shift+alt+m+n+o` or use multiple keystrokes like `ctrl+a,shift+b` and you can also write this as `ctrl+a, shift+b` (mind the whitespace).
I am not sure if this is possible to type in TypeScript. If you have an idea about this, I'd appreciate some input :)

**Comment by CodingDive** [comment]
No idea. I wanted to read the handbook for a long time. I might get to it soon and'll let you know if I find any magic TypeScript string concatination hacks 😀

**Comment by JohannesKlauss** [comment]
As far as I know this isn't possible, but of course, I could be wrong.
I'll close this for now, but if you find a way feel free to reopen it.
