### ISSUE TITLE
Callback approach

### ISSUE THREAD

**Issue by AshotN** [JohannesKlauss/react-hotkeys-hook#197]
The docs https://johannesklauss.github.io/react-hotkeys-hook/docs-use-hotkeys#memoisation here say to use a Callback approach and avoid defining a dependency array. But I can't figure that out.

    useHotkeys('space', () => log(playerStatus), [playerStatus]);

works just fine, but how should it look

**Comment by JohannesKlauss** [comment]
Hey @AshotN 
Your solution is just fine. The Avoidance of the dependency array is specific to updating the state in the `useState` hook.

**Comment by AshotN** [comment]
I see. It’s to avoid an effect causing an effect? Cool. Thank you
