### ISSUE TITLE
Testing these hooks inside a component

### ISSUE THREAD

**Issue by louisrli** [JohannesKlauss/react-hotkeys-hook#198]
Could you give an example of how you could test these hooks if they're used inside a component?

For example, I can't figure out how to test a component that uses this with react testing library [fireEvent](https://testing-library.com/docs/dom-testing-library/api-events).

It looks like the original lib somehow creates a dummy component or something that events get fired against; any tips on how to find that component to listen to it in my test?

**Comment by JohannesKlauss** [comment]
I don't quite understand. You would have to use a e2e testing framework like [Cypress.io](https://www.cypress.io/) to mount the component and trigger key strokes.

**Comment by louisrli** [comment]
Hmm, yeah, I guess what I was saying was that you should be able to unit test these types of things in a react component rather than using a browser test

**Comment by JohannesKlauss** [comment]
Well this is not so much a problem with this package, but with hooks in general. If you want to test a hook via unit test, build a wrapper like this:
https://dev.to/itsjoekent/write-functional-tests-for-react-hooks-4b07
