### ISSUE TITLE
Don't set wrong examples without warning

### ISSUE THREAD

**Issue by franciscop-sc** [JohannesKlauss/react-hotkeys-hook#200]
The first code example in [the section Memoisation](https://johannesklauss.github.io/react-hotkeys-hook/docs-use-hotkeys#memoisation) seems to be wrong _on purpose_.

This is very dangerous from a drive-through point of view, many devs will arrive from Google and copy/paste the example, which actually works once so they might call it a day. [Users don't read the text](https://uxmyths.com/post/647473628/myth-people-read-on-the-web) so I'd recommend either not displaying broken code snippets or adding a big warning in a comment like `// DOES NOT WORK`.

**Comment by JohannesKlauss** [comment]
@franciscop-sc thanks for the comment, you're right I will update the docs.
