### ISSUE TITLE
react-hotkeys-hook js distributions don't support IE.

### ISSUE THREAD

**Issue by Wallysburg** [JohannesKlauss/react-hotkeys-hook#212]
Hello!

First of all, thanks for creating this useful package.

Unfortunately, default parameters aren't supported by any version of IE, so any project that is consuming this project won't be able to support IE. While I dream of a world where web devs will no longer have to support IE, this is sadly not going to be a reality for years to come.

The problem is that the current build for react-hotkeys-hook is targeting es2018 which outputs a javascript dist that contains the usage of default parameters:

```javascript
import hotkeys from 'hotkeys-js';
import { useCallback, useEffect } from "react";
export function useHotkeys(keys, callback, deps = []) {
    const memoisedCallback = useCallback(callback, deps);
    useEffect(() => {
        hotkeys(keys, memoisedCallback);
        return () => hotkeys.unbind(keys, memoisedCallback);
    }, [memoisedCallback]);
}
```

Fortunately, the fix here would be to simply change the target parameter within the tsconfig.json to target es2015 instead. This would ensure that the distributed js would be supported by more antiquated browsers like IE.

**Comment by JohannesKlauss** [comment]
@Wallysburg Thx for creating the issue. I will dig into that. At first glance it seems that pika pack is ignoring the target of the tsconfig, but I need to look into that.

**Comment by ypresto** [comment]
There is no config to output es2015 or es5 with `@pika/plugin-ts-standard-pkg` and `@pika/plugin-build-web`. `@pika/plugin-bundle-web` is the only way to do that but all node_modules will be bundled to a single file.

**Comment by giuvincenzi** [comment]
With webpack and babel this could be the solution:
```js
{
  test: /\.js$/,
  exclude: /node_modules(?!(\/react-hotkeys-hook))/,
}
```

**Comment by reidphilpot** [comment]
👍 upvote for fixing this transpiling issue, thanks

**Comment by JohannesKlauss** [comment]
@ypresto Yeah you are right. There is unfortunately not much I can do about. I'd have to replace the whole building and publishing system.
Will think about that.

**Comment by JohannesKlauss** [comment]
@Wallysburg @reidphilpot For the time being I removed the usage of default parameters to fix this issue. Please check if 2.1.2 works for you in IE and let me know if there are any issues.

**Comment by joshwreford** [comment]
I'm using v2.1.3 and I'm still getting webpack errors thrown in IE11. Has anyone else had better luck?

**Comment by JohannesKlauss** [comment]
@joshwreford can you pinpoint what is causing the error?

**Comment by JohannesKlauss** [comment]
@joshwreford Can you check out v2.3.0 and try it in IE11?
