### ISSUE TITLE
[Question] How do you specify `cmd` or `ctrl` depending on the OS?

### ISSUE THREAD

**Issue by chrisrzhou** [JohannesKlauss/react-hotkeys-hook#220]
Hi there!

Is there a way to automatically assign `cmd/ctrl` depending if the OS is Windows/Mac/Linux?

Currently, to support both, I'm declaring this twice:

```js
useHotkeys('ctrl+c', () => copyHandler());  // Windows
useHotkeys('cmd+c', () => copyHandler());  // Mac
```

This is still not ideal and the best scenario is for `react-hotkeys` to figure out if `ctrl`/`cmd` should be used depending on the OS

```js
useHotkeys('<MAGIC_KEY??>+c', () => copyHandler());  // defined just once
```

What would be the recommended way to go about approaching this?

Thank you!

**Comment by JohannesKlauss** [comment]
You can just separate them with a comma like this:
`useHotkeys('ctrl+c, cmd+c', () => copyHandler());  // Windows & Mac`
