### ISSUE TITLE
Add ability to pass options

### ISSUE THREAD

**Issue by amcdnl** [JohannesKlauss/react-hotkeys-hook#234]
Need to enhance to include ability to pass options - https://github.com/jaywcjlove/hotkeys#option

**Comment by JohannesKlauss** [comment]
@amcdnl This will be available in version 2.0 which will be released later that day.

**Comment by JohannesKlauss** [comment]
I just released version `2.0.1` which include the ability to pass options. Pls note that the `deps` and `options` parameter have switched places in v2
