### ISSUE TITLE
Stale state when using Context API

### ISSUE THREAD

**Issue by amanharwara** [JohannesKlauss/react-hotkeys-hook#239]
When using the Context API, it does not use the updated value and sticks to the initial one.

Here is some example code where this happens:

```tsx
const Component = () => {
	const {state, setState} = useContext(ContextObject);
	
	// Initial state is:
    // { a: 1 }

	// Update state to { a: 2 }
	useEffect(()=>{
		setState({
			a: 2			
		});
	}, []);

	useHotkeys('ctrl+b', ()=>{
		console.log(state); //Logs: { a: 1 }
	});
}
```

Am I doing something wrong or is this a bug?

**Comment by jordymeow** [comment]
Did you find an elegant solution for this @amanharwara ?

**Comment by amanharwara** [comment]
@jordymeow I haven't used that code in a while so I don't remember exactly but I think it's as simple as adding something to the dependency array in the end.

Check out the [Parameters](https://github.com/JohannesKlauss/react-hotkeys-hook#parameters) section from the README. It has more information about the dependency array.

Also, I think you have to be careful what variable you add as a dependency. I remember adding the whole state variable as a dependency and my app froze because it went into a never-ending loop.

**Comment by jordymeow** [comment]
Yes indeed, found it right after asking you in fact :) It works fine. Thanks a lot for your reply too! It works exactly the same way as the standard hooks in React, such as useMemo, useEffect, etc.
