### ISSUE TITLE
useHotkeys props order

### ISSUE THREAD

**Issue by danielfroz** [JohannesKlauss/react-hotkeys-hook#260]
Hi, Would like to suggest a code change... implications may be huge... But still valid the effort i think.

Most of the time I am in a situation where need to pass {} to options due to it's place in Function props order....
```
useHotkeys('f5', () => {
        history.replace(`/customer/${customer.id}/order`)
 }, {}, [ customer ])
```

Honestly Callback's memoization is more important than options... I mean, in almost 99.99% cases I find myself using the options' default values...

Here snipped that reflects the change applied to project's code..
```
[...]
useHotkeys(
  keys: string,
  callback: KeyHandler,
  deps?: any[],
  options?: Options,
)
[...]
```

Going back to my example... simple change but may have a great impact on code.
```
useHotkeys('f5', () => {
        history.replace(`/customer/${customer.id}/order`)
}, [ customer ])
```

BTW, I am only suggesting this change since sometimes, coding fast I completely forget to pass {} or null as options; then I get error messages like this...
```
Uncaught TypeError: Array.prototype.filter called on null or undefined
    at filter (<anonymous>)
    at dispatch (hotkeys.esm.js:338)
    at HTMLDocument.<anonymous> (hotkeys.esm.js:512)
```
This due to passing filter options to hotkeys-js ....

Would prefer to see this reflected on this great project than in my private Git cloned revision ;-)

Thanks!

**Comment by JohannesKlauss** [comment]
@danielfroz Thanks for your report and you are right, this can be annoying.

I overloaded the hook in version 2.1.3 I just released.
The signature now is

```ts
export function useHotkeys(keys: string, callback: KeyHandler, options?: Options): void;
export function useHotkeys(keys: string, callback: KeyHandler, deps?: any[]): void;
export function useHotkeys(keys: string, callback: KeyHandler, options?: Options, deps?: any[]): void;
```

So you can just omit the empty options object and the hook will determine by itself if it's a deps array or the options object as third argument.
Please let me know if you encounter any problems.
