### ISSUE TITLE
[Question] iframe hotkey

### ISSUE THREAD

**Issue by ricardona** [JohannesKlauss/react-hotkeys-hook#269]
When creating a web page and then embedding an iframe, the hotkey does not work within this frame. Could you please tell me what I could do to make the parent document hotkey work inside the iframe?

Thanks in advance.

**Comment by JohannesKlauss** [comment]
Is the hotkey hook used inside the iframe?

**Comment by ricardona** [comment]
The hotkey is in the parent document. So when opening an iframe this hotkey doesn't work. Is it possible to inject this hotkey into the iframe?

Thanks @JohannesKlauss

**Comment by JohannesKlauss** [comment]
No. This is not possible due to security concern. Parent cannot access child iframes in any way. Otherwise you could create a site, display a banking page via iframe and then just grab all credentials the user inputs.
