### ISSUE TITLE
Support for hotkey-js scope is missing

### ISSUE THREAD

**Issue by evanwalsh** [JohannesKlauss/react-hotkeys-hook#290]
`hotkey-js` allows you to set a scope with `hotkeys.setScope` and retrieve it via `hotkeys.getScope`. With the new options passing added in, I can define a scope. However, I cannot change from the default `all` scope. If you'd like me to make a PR to add this in, let me know!

**Comment by JohannesKlauss** [comment]
@evanwalsh My hands are pretty tight right now. If you find the time to create a PR for this, it would be more than welcome.

**Comment by JohannesKlauss** [comment]
Closing this due to the fact that version 4 won't have hotkeys-js as the base package. Until then scoping support won't be supported, but we will likely add support for a similar idea in version 4.
