### ISSUE TITLE
Use of brackets and "æøå"

### ISSUE THREAD

**Issue by Zenjjim** [JohannesKlauss/react-hotkeys-hook#295]
I am creating a project in Norwegian, and wish to add "alt + å" as a hotkey. When i use useHotkeys('*', (e) => console.log(e)); i can see that it is listening to the keypress å and I get an output. However if I use the same hook with useHotkeys('å', (e) => console.log(foo)), i get no output.

**Comment by Zenjjim** [comment]
The norwegian "å" is equivalent to "{" in the standard keybord config

**Comment by JohannesKlauss** [comment]
@Zenjjim thanks for the bug report. This package is just wrapping a hook around the [hotkeys.js](https://github.com/jaywcjlove/hotkeys) package. So this bug should be raised there. As soon as it as fixed I can make use of the new hotkeys package and update this wrapper.
