### ISSUE TITLE
enableOnTags example

### ISSUE THREAD

**Issue by kosijer** [JohannesKlauss/react-hotkeys-hook#309]
Can anyone give an example of using enableOnTags or filters option please? I'm trying to make the library work over the `input` field but no luck so far. Thank you

My code looks like this now

```

  useHotkeys(
    "command+f, ctrl+f, f3",
    (e) => {
      e.preventDefault();
      setOpenFilters((openFilters) => !openFilters);
      (document.getElementsByClassName(
        "input-sm"
      )[0] as HTMLInputElement)?.focus();
    }
  );
```

**Comment by JohannesKlauss** [comment]
For the enableOnTags feature you would do something like this:

`useHotkeys('a', onPress, {enableOnTags: ['INPUT']});`

The `filter` option is ignored if you use `enableOnTags`.
Basically `enableOnTags` just acts as a generic implementation of the `filter` option for the hotkeys.js library.

You would use the `filter` option if you want to have a custom implementation.
Check out the hotkeys.js docs for that: https://wangchujiang.com/hotkeys/
