### ISSUE TITLE
Numberpad keys are not being detected even thou the numbers keys on top of keyboard work fine.

### ISSUE THREAD

**Issue by akashraj9828** [JohannesKlauss/react-hotkeys-hook#316]
The code for numberpad are also "1","2","3".... and for the number keys on top are also same. When i write 

```
	useHotkeys("1,2,3,4,5", (event) => {
		//this only logs for numbers keys on top and not the numpad keys
		console.log(event);
	});

```

**Comment by JohannesKlauss** [comment]
This hook is just a wrapper for hotkeys-js.
If keys are not detected, that would be an issue to raise in the hotkeys js repo
