### ISSUE TITLE
How to ignore repeating keyboard event

### ISSUE THREAD

**Issue by Taymindis** [JohannesKlauss/react-hotkeys-hook#327]
I am trying to migrate my Application from `react-hotkeys`. 

I am wondering by any chance to have a options like 

`ignoreRepeatedEventsWhenKeyHeldDown: boolean` 

in react-hotkeys-hook?

**Comment by JohannesKlauss** [comment]
Using `useHotkeys(key, handler, {keyup: true})` should work for you. This way the handler gets triggered when there is a keyup event.

**Comment by Taymindis** [comment]
@JohannesKlauss 

It did solve the issue, but what I want is when pressing down and holds it I will put dictionary notification for the user.

I saw `e.repeat` this might good for you to have an idea for this option feature?

```jsx
 const [c, setC] = useState(0);
  useHotkeys('enter', (e, ke) => {
    console.log(e.repeat);
    setC(c + 1)
  }, [c])
  return (
    <div className="App">
      <h1>Hello CodeSandbox {c} </h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  ); 
```

**Comment by JohannesKlauss** [comment]
I don't quite understand what your issue is. Could you elaborate? You can either detect a key event via keydown or via keyup. Or both, whatever you want. What the handler does is up to you.

**Comment by Taymindis** [comment]
I am wondering if we can have an option like `keyDownAndHold: true`, and event trigger once only. 

However, I would go with keydown and e.repeat to achieve this scenario.

**Comment by michaeljblum** [comment]
Yeah I was trying to achieve something similar to what @Taymindis was looking for I believe. Even with the `{keyup: true}` config, you still get loads of repeated function calls if you hold the specific key combo. I wanted the function to be called just once, irregardless of how long the user presses/holds the specific key combo.

For anyone looking to accomplish this: `(e) => !e.repeat && exampleFunc()`, without the keyup  config in the next argument, seems to work.

**Comment by mattbf** [comment]
Same here, I'm trying to implement a continuous scroll event by holding down the "j" key. Right now, no matter what I set my keyup/keydown settings to, the event is only fired once (twice if both keyup and keydown are true)  when holding the key down.

Is there anyway to achieve this? Looks like event.repeat is always false coming from the useHotkeysEvent

**Comment by blentz100** [comment]
@michaeljblum Great tip. That's exactly what I came here looking for.

**Comment by cdt-eth** [comment]
did you find a solution @mattbf? i'm looking to do the exact same thing.

**Comment by JohannesKlauss** [comment]
Why not have two listeners? One listens to keydown, the other to keyup. The first listener triggers the scrolling and the the second one stops it.

**Comment by mattbf** [comment]
> Why not have two listeners? One listens to keydown, the other to keyup. The first listener triggers the scrolling and the the second one stops it.

@cdt-eth this is what I ended up doing
