### ISSUE TITLE
events fired via shortcut keys are unable to read the current state of the components.

### ISSUE THREAD

**Issue by KalpeshPopat** [JohannesKlauss/react-hotkeys-hook#329]
i was using v2.1.3 and events fired via shortcut keys were unable to read the current state of the components. So i changed to latest version 2.2.2 but the bug persist

**Comment by JohannesKlauss** [comment]
Are you using the deps array for the `useHotkeys`hook? Otherwise your state will be stale, since it uses `useCallback` under the hood.

**Comment by KalpeshPopat** [comment]
This is the code that i am using. dependency array is not passed, however i tried to pass a blank [] array and have the same results. 

We have decided to go away from the hook concept for hot keys and instead will be integrating the javascript file directly into the code, since we need conditional execution of the hotkey based on configuration.

`import React from 'react'
import { useHotkeys } from 'react-hotkeys-hook'

//This component will require key value pair of data
const SarasTabsRow = (props) => {
    const { row, index, isActive, onClick, enableHotKeys } = props;

    // console.log("tab component row", row, index, isActive);
    const onTabClick = (e) => {
        let tabKey = row.key;// e.currentTarget.getAttribute("tabKey");
        // console.log("on tab click row", tabKey);

        if(onClick) onClick(e, tabKey);
    }

    //TODO replace the hook version of hot keys with javascript version to enable conditional execution
    // if(enableHotKeys || enableHotKeys == undefined){
        useHotkeys(`${index}`, onTabClick, []);
    // }

    return (
        <li tabKey={row.key} key={index}
            onClick={onTabClick}
            className={`uiTabRow ${isActive ? 'uiTabActive' : ''}`} 
        >
            <span className="uiTabContent">{`${row.val} (${index})`}</span>
        </li>
    )
}

const SarasTabs = (props) => {
    const { dataList, onChange, defaultKey, enableHotKeys} = props;
    const [activeTabKey, setActiveTabKey] = React.useState(defaultKey);

    // console.log("tabs component", dataList, defaultKey);

    //raise event only if a different tab was clicked 
    //- to ensure api calls are triggered only for a change and not for every click
    const onTabClick = (e, tabKey) => {
        console.log("on tab click parent outside if", activeTabKey, tabKey);
        if(activeTabKey != tabKey){
            setActiveTabKey(tabKey);
            console.log("on tab click parent inside if", tabKey);
            if(onChange) onChange(tabKey);
        }
    }
    
    if(dataList != undefined && dataList != null)
    {
        return (
            <div id="searchGroupList" className="uiTabContainer" runat="server">
                <ul role="tablist" className="uiTab">
                    {
                        dataList.map((row, index) => (
                            <SarasTabsRow row={row} key={index} index={index + 1} 
                            isActive={(row.key === activeTabKey)} onClick={onTabClick} enableHotKeys={enableHotKeys}/>
                        ))
                    }
                </ul>
            </div>
        )
    }
    else{
        return null;
    }
}

export default SarasTabs;
`

**Comment by KalpeshPopat** [comment]
i have solved this problem by instead creating a custom wrapper component for Hotkeys, that also gives me flexibility to implement a conditional execution - as i wanted to disable hotkeys on a button if shortcut is not configured.

**Comment by JohannesKlauss** [comment]
You have to pass your dependencies otherwise you will get a stale state. It works just like `useMemo` or `useCallback`.

```js
useHotkeys(`${index}`, onTabClick, [row, onChange]);
```

**Comment by KalpeshPopat** [comment]
Thanks. got it.
