### ISSUE TITLE
single `alt` key is not working?  

### ISSUE THREAD

**Issue by Taymindis** [JohannesKlauss/react-hotkeys-hook#332]
I have a hot key with alt only, but it is not working though

**Comment by JohannesKlauss** [comment]
Could you please give bit more context and a code example?

The alt key is seen as a modifier, so I don't think that you can listen to it directly. You would have to use the asterik as a wild card to listen to all keys and then check if the alt key is pressed:

`useHotkeys('*', e => console.log('is altKey?', e.altKey));`

**Comment by Taymindis** [comment]
@JohannesKlauss 

I think i got your answer.

**Comment by jamesmoss** [comment]
This just tripped me up for an hour or so. I can't see any reason why this isn't supported out the box. It triggers a keydown event just like any other key.

**Comment by JohannesKlauss** [comment]
@jamesmoss This is because the underlying package is hotkeys.js.
I had plans to build my own solution or switch the base package, but I am too busy right now.

**Comment by tslater** [comment]
I'm currently binding an number input. My use case is to use shift to change the step. I'd like to show the user a visual indicator when the shift key is being held down. However, using `'*'` binds all keys so typing in number, hitting the delete key, etc. no longer work. Is there a way to propagate the event? I tried returning `true` from the callback with no luck.

**Comment by JohannesKlauss** [comment]
you can set a react state inside the callback and just use `shift` as the key.
