### ISSUE TITLE
how  Dynamic Settings shortcuts?

### ISSUE THREAD

**Issue by nuts-cake** [JohannesKlauss/react-hotkeys-hook#337]
If I get the shortcut key I need in an asynchronous request, but I iterate through the requested data in the FC and iterate over it, an exception will be thrown.
`
 keyCustomArr.forEach((item) => {
    useHotkeys(item.key, item.fn);
  });
`
![image](https://user-images.githubusercontent.com/57939875/90476525-40e1c480-e15c-11ea-94bf-a348cb9c7e71.png)
![image](https://user-images.githubusercontent.com/57939875/90476552-4dfeb380-e15c-11ea-8cb9-c03f5ecea3cf.png)

**Comment by nuts-cake** [comment]
error:Warning: React has detected a change in the order of Hooks called by MainPage. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks:

**Comment by JohannesKlauss** [comment]
This is not a bug, you are using hooks wrong. There are three rules to using hooks and one of them is to not write them conditionally. See this page for mor info https://reactjs.org/docs/hooks-rules.html
