### ISSUE TITLE
Remove node limitation

### ISSUE THREAD

**Issue by Romroot** [JohannesKlauss/react-hotkeys-hook#349]
Hello, 

In our project, we are using node v10, so we can't use node v12 that you added in engine.  But it don't mean that your library won't work on node with smaller version.
Can we please do one of the options?
1.) remove this engine section in pre-publish
2.) or remove it in section and simply add it to documentation?

If you are busy I can create PR on it.

![image](https://user-images.githubusercontent.com/48890185/91971620-2d208b80-ed22-11ea-88ea-c45214c848b6.png)

**Comment by JohannesKlauss** [comment]
I have my hands pretty full, but PRs are welcome. Should be an easy one :)

**Comment by JohannesKlauss** [comment]
The restriction has been removed in version 2.3.1
