### ISSUE TITLE
Combination Hotkeys

### ISSUE THREAD

**Issue by gamevnlc** [JohannesKlauss/react-hotkeys-hook#360]
I have created three child components, each component I assign to a hotkey. 
Child component A hotkey q
Child component B hotkey w
Child component C hotkey e
When `useHotkeys` on hotkey it will changing the component color. I want to create a combination of `q+w+e` to change color on child components. Is there any way to do it without creating new `useHotkeys`

Thanks

**Comment by JohannesKlauss** [comment]
You can combine hotkeys by separating them with a comma.

`useHotkeys('q, w, e', () => /* change color */, []);`

See this codesandbox for example: https://codesandbox.io/s/eloquent-ramanujan-e8iqn

**Comment by gamevnlc** [comment]
Nice, thanks. I haven't think about writing the key combination like that

**Comment by gamevnlc** [comment]
I have multiple child components when I try this code below on child components it doesn't work
```
const [index, setIndex] = useState(0);
    useHotkeys(
        "q, w, e",
        (event, handler) => {
            console.log(handler.key);
            setIndex((index + 1) % 3);
        },
        [index]
    );
```

When I set it in parent component it work ok. Do you know why ?
@JohannesKlauss

**Comment by gamevnlc** [comment]
nvm, I forgot to attach dependency
