### ISSUE TITLE
It seems options are not getting passed through.

### ISSUE THREAD

**Issue by aeschylus** [JohannesKlauss/react-hotkeys-hook#389]
Following the example from the hotkeys documentation referenced in the react-hotkeys-hook documentation [here](https://github.com/jaywcjlove/hotkeys/#keyup), and taking into account the switched position of `deps` and `options` [docs](https://johannesklauss.github.io/react-hotkeys-hook/docs-use-hotkeys#parameters), I have tried the following code:

```javascript
hotkeys('enter', function(event, handler) {
 console.log(handler);
}, [],  {keyup: true});
```

However, this returns the following to the console:
<img width="302" alt="Screenshot 2020-10-26 at 1 13 49 AM" src="https://user-images.githubusercontent.com/145874/97143951-9eccf280-1731-11eb-924e-62b06ce81496.png">

I've also tried other combinations, but none work (thinking of these lines: https://github.com/JohannesKlauss/react-hotkeys-hook/blob/master/src/useHotkeys.ts#L15-L22). Am I doing something wrong?

**Comment by JohannesKlauss** [comment]
You have to use the hook via `useHotkeys`, not `hotkeys.`

**Comment by aeschylus** [comment]
I've update the code I posted. I am using the hook. I'll set up a sandbox.

**Comment by JohannesKlauss** [comment]
@aeschylus Your options and deps parameters are in the wrong place, you have to switch them. The fourth parameter only will be inferred as a deps array.

**Comment by JohannesKlauss** [comment]
I released a new version https://github.com/JohannesKlauss/react-hotkeys-hook/releases/tag/2.4.0 that changes that behavior.

Now you can only set keyup and it won't trigger twice: https://codesandbox.io/s/vibrant-bohr-e6yhz?fontsize=14&hidenavigation=1&theme=dark
