### ISSUE TITLE
Use with Portal / outside DOM ?

### ISSUE THREAD

**Issue by larissa-n** [JohannesKlauss/react-hotkeys-hook#405]
Trying to find a way to use this with multiple windows. I tried including the hook in portal children: https://codesandbox.io/s/popout-hotkeys-ysqz6?file=/pages/index.js, and including the hook in the portal / popout definition itself: https://codesandbox.io/s/popout-hotkeys-forked-m4i8y, but neither worked. Any ideas how to solve this?
Thank you!

**Comment by JohannesKlauss** [comment]
Hi @larissa-n 
Sorry for the late reply, I was pretty busy. I have to investigate this, seems like a bug that is happening in the underlying hotkeys-js package. I'll get back to you.

**Comment by JohannesKlauss** [comment]
The hook is now compatible with Portals: https://codesandbox.io/s/xenodochial-darkness-k2ud2t

What you are trying to do is to use hotkeys defined in one window inside another. So in order to make that work you have to use the hotkeys hook inside that new window.

**Comment by larissa-n** [comment]
@JohannesKlauss thank you! Great work separating the library from hotkeys-js and expanding the API!

The [document](https://react-hotkeys-hook.vercel.app/docs/api/use-hotkeys#document) option is very helpful here - this portal is rendered outside the DOM in another window's `document`. Very excited the active `document` can be specified now so the listener doesn't just get attached to the parent DOM's `document`. Great!
