### ISSUE TITLE
Triggers while focussed on input field since v3.0.0

### ISSUE THREAD

**Issue by laurensnl** [JohannesKlauss/react-hotkeys-hook#438]
Since updating to v3.0.0, the hotkeys also trigger while entering text in an input field.

I use the hook like this:

```
useHotkeys('d', () => toggle());
```

**Comment by alperen** [comment]
We caught the same.

**Comment by JohannesKlauss** [comment]
Weird, I'll look into it.

**Comment by JohannesKlauss** [comment]
Fixed in 3.0.1

**Comment by richardsolomou** [comment]
@JohannesKlauss This seems to still be affecting elements with `contenteditable`

**Comment by laurensnl** [comment]
After the update to v3.0.1, I get this error when pressing a hotkey while focussed on an input field:

```
Cannot read property 'enableOnTags' of undefined
```

**Comment by houmark** [comment]
I can confirm getting the same error as @laurensnl

**Comment by JohannesKlauss** [comment]
I am sorry, I'll look into it. Shouldn't create a major update before the holidays, haha.

**Comment by JohannesKlauss** [comment]
Should be fixed with 3.0.2

**Comment by JohannesKlauss** [comment]
Fixed with 3.0.3

**Comment by laurensnl** [comment]
Thanks @JohannesKlauss! I can confirm that everything works as expected now.  🎉

**Comment by richardsolomou** [comment]
@JohannesKlauss This is still affecting elements with `contenteditable`

**Comment by JohannesKlauss** [comment]
@richardsolomou I'll try to have a look at it over the weekend.

**Comment by rvrheenen** [comment]
> @JohannesKlauss This is still affecting elements with `contenteditable`

I have the same problem, and having a hard time to find a workaround. I would very much appreciate it you would be able to include this 🙏🏻

**Comment by JohannesKlauss** [comment]
Finally fixed this behavior.
If a target element has its `contentEditable` attribute set to `true`, hotkeys won't trigger.
