### ISSUE TITLE
Using wildcard (*) gives 'length' of undefined at dispatch error.

### ISSUE THREAD

**Issue by Parjoona** [JohannesKlauss/react-hotkeys-hook#439]
I am building a functionality where a user can customize their hotkeys in a settings menu, and is picking up the wanted hotkeys by using the wildstar property to do so.

When React changes from this settings page, to any other page, it does not seem like the hotkeys hook unmounts.
I am using v.3 of the library.

This is the hook setup I use on the settings page.
And pick up the keys in input fields using the bindingReferance value.

``` 
useHotkeys(
    '*',
    ({ key, altKey, ctrlKey, shiftKey }: KeyboardEvent) => {
      const keyBind: string[] = [];

      if (ctrlKey) keyBind.push('ctrl');

      // This is to sort out key presses
      if (!['Control'].includes(key)) keyBind.push(key);

      const binding = keyBind.join('+');
      bindingReferance.current = binding || null;
    },
    { enableOnTags: ['INPUT'] }
  );
```

But as I said, when changing from this page to any other page,
I would get this error

hotkeys.common.js:429 Uncaught TypeError: Cannot read property 'length' of undefined
    at dispatch (hotkeys.common.js:429)
    at HTMLDocument.<anonymous> (hotkeys.common.js:516)

This is the use for the other buttons, for example in the navigation menu.
`useHotkeys(hotkey, () => push(to));`

So my theory is that it doesn't unmount the wildstar useHotkeys hook, and maybe overwrites the useHotkeys hooks I placed in my navigation buttons

**Comment by JohannesKlauss** [comment]
Could you clarify where you are checking for the user key and function that gets invoked?

Also I see that you are using a `bindingReference` variable. You have to include this as a dependency. Otherwise the ref won't get updated inside the callback.
The callback you are passing is memoised inside the hook, so it works just like `useCallback` or `useEffect`.

**Comment by Parjoona** [comment]
Thanks, that was a good solve!
