### ISSUE TITLE
Incorrect URLs in docs

### ISSUE THREAD

**Issue by JB1905** [JohannesKlauss/react-hotkeys-hook#441]
Incorrect links in docz menu e.g.:

Instead of `https://johannesklauss.github.io/react-hotkeys-hook/docs-use-hotkeys/` I get `https://johannesklauss.github.io/docs-use-hotkeys`

This is probably a problem with base in doczrc

**Comment by JohannesKlauss** [comment]
Thanks for reporting. I'll look into it.

**Comment by JohannesKlauss** [comment]
Finally fixed that error.
