### ISSUE TITLE
Feature request: support an enabled option

### ISSUE THREAD

**Issue by ggascoigne** [JohannesKlauss/react-hotkeys-hook#480]
Since this is a hook, and therefore can't be made conditional, it would be extremely useful if there was an enabled or disabled option in the Options.  There are times when I don't want to add keybindings for a reusable component because I know that they'll clash with other ones that are in scope, right now I add them in a junk scope, but it would be much clearer to have an option to just disable the call.

**Comment by JohannesKlauss** [comment]
Would the filter option suit you? You can give a function to the filter property where you can return false if you don't want the callback to trigger.

**Comment by ggascoigne** [comment]
That seems to be working nicely, thanks for the work around.

**Comment by JohannesKlauss** [comment]
No problem, you're welcome.

**Comment by ggascoigne** [comment]
I should add that this actually only works correctly as a disable option if you also pass through `filterPreventDefault: false`.

Would you mind a PR that adds an enabled flag to options?  Defaulting to true, and if it's false, that just bailes out of the hook before it installs anything?

Having to add a filter as well as a second flag everywhere is ending out sort of messy.

**Comment by JohannesKlauss** [comment]
Sure, I get your point. Would you submit a PR?

**Comment by JohannesKlauss** [comment]
Fixed with 3.2.0
