### ISSUE TITLE
how to use numpad?

### ISSUE THREAD

**Issue by zcaalock** [JohannesKlauss/react-hotkeys-hook#494]
i want to set shift+num_1, how to do it?

here is reference
https://github.com/jaywcjlove/hotkeys/issues/96

**Comment by Nikhil-yadav-90** [comment]
I am also facing the same issue in setting up my numpad keys enter is working fine in the numpad but numbers are not assigning to the function of numpad

**Comment by JohannesKlauss** [comment]
I think this is currently not supported. I'll have a look as soon as poosible.

**Comment by JohannesKlauss** [comment]
hotkeys.js added the support for this in its newest version which gets shipped with the `3.3.0` version of this hook.
