### ISSUE TITLE
Question: Hot Key not propagating when checkbox is focused, any idea how to force? 

### ISSUE THREAD

**Issue by shawnmitchell** [JohannesKlauss/react-hotkeys-hook#505]
I don't believe this is a bug but I'm trying to figure out how to stop keyboard events from getting swallowed up by a focused checkbox. Anyone run into this challenge before and come up with a good solution?

**Comment by JohannesKlauss** [comment]
Hi @shawnmitchell 
You would use the `filter` and `filterPreventDefault` options to achieve this:

```js
useHotkeys(key, callback, {
    filter: ev => ev.target?.type === "checkbox" || ev.target?.tagName !== "INPUT",
    filterPreventDefault: false,
    enableOnTags: ["INPUT"]
});
```

Check this sandbox out https://codesandbox.io/s/hopeful-sun-n7xjc?file=/src/App.tsx

**Comment by shawnmitchell** [comment]
Thanks so much!
