### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by allenbrubaker** [JohannesKlauss/react-hotkeys-hook#51]
I think I'm getting an infinite loop because you're not adding the second parameter [] at the end of the useEffect in your code.  This will only register the event handler (hotkey) once instead of every single render.

**Comment by JohannesKlauss** [comment]
@allenbrubaker Good catch. It's not so much an infinite loop but is binds and unbinds on every render. I'll fix that.

**Comment by JohannesKlauss** [comment]
Fixed in 1.3.0 release. Thank you for opening the issue.
