### ISSUE TITLE
Param to allow hotkeys in contenteditable?

### ISSUE THREAD

**Issue by olhapi** [JohannesKlauss/react-hotkeys-hook#511]
Hello @JohannesKlauss. I saw you disabled hotkeys for `contenteditable` in #438. Any way I can enable my hotkey inside `contenteditable` with `enableOnTags` or something?

**Comment by JohannesKlauss** [comment]
Hi @olhapi,
currently it is completely disabled. May I ask what the use case would be to enable hotkeys in a contenteditable field?

**Comment by olhapi** [comment]
Thx for reply @JohannesKlauss I want to use `ctrl+s` to save data in wysiwyg without changing focus. I can live without it, but it's nice feature to have.

**Comment by JohannesKlauss** [comment]
Makes sense. I'll check how wer could clenaly re enable this

**Comment by olhapi** [comment]
Much appreciated.

**Comment by JohannesKlauss** [comment]
Fixed in `3.3.1`

You can now write something like this:

```js
() => {
    const [amount, setAmount] = useState(0);
    useHotkeys('cmd+s', (e) => {
      e.preventDefault();
      setAmount(prevAmount => prevAmount + 100);
    }, {enableOnContentEditable: true});
    return (
      <>
        <div>
          {amount >= 0 ? 'Add' : 'Remove'} {Math.abs(amount)} dollars {amount >= 0 ? 'from' : 'to'} my bank account.
        </div>
        <div contentEditable={true}>Edit this text.</div>
      </>
    );
  }
```

**Comment by yigitkeremoktay** [comment]
Hey, there is a little issue that I have found. The option `enableOnContentEditable` definitely seems to be working totally fine with non-inputs with `contentEditable={true}` however when using a normal `<input>`, the option doesn't work and the hotkey is not triggered. Is this a limitation of JavaScript or is it is just a bug/choice of the library?

**Comment by JohannesKlauss** [comment]
You have to use the `enableOnTags` option as mentioned here:
https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/disable-hotkeys#enable-hotkeys-on-form-fields

`contentEditable` is unrelated to input tags.

**Comment by yigitkeremoktay** [comment]
> @yigitkeremoktay, you have to use the `enableOnTags` option as mentioned here: https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/disable-hotkeys#enable-hotkeys-on-form-fields
> 
> `contentEditable` is unrelated to input tags.

Thanks very much for your quick reply. Really appreciate your support.
