### ISSUE TITLE
Hotkey not working on radio button

### ISSUE THREAD

**Issue by gamevnlc** [JohannesKlauss/react-hotkeys-hook#513]
I using the `space` to trigger the event to change background color but when I click on the radio button and press the `space` nothing happened. The radio button displays the focus visible only. Is there any way to prevent it?
demo: https://codesandbox.io/s/fast-tdd-exfon

**Comment by JohannesKlauss** [comment]
Hi @gamevnlc 
You can use the `enableOnTags` options as shown here:
https://codesandbox.io/s/funny-sun-kxq4r

**Comment by gamevnlc** [comment]
@JohannesKlauss awesome thanks

**Comment by gamevnlc** [comment]
@JohannesKlauss Hello 
I set the `enableOnTags` options the keyboard event only triggers when I click on the input radio button. 
I want to trigger the keyboard event when the input radio button is either focused or not focus. Is there any way to do it?
