### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by Seanmclem** [JohannesKlauss/react-hotkeys-hook#525]
Hi, I tried

  useHotkeys('ctrl+s', () => { handleSave() });
and

  useHotkeys('cmd+s', () => { handleSave() });

and the default behavior always fires

tried this too

useHotkeys('ctrl+s', () => { handleSave() }, { filterPreventDefault: false });
useHotkeys('cmd+s', () => { handleSave() }, { filterPreventDefault: false });

**Comment by JohannesKlauss** [comment]
If you want the default behavior to not trigger you need to call that in you callback:

```js
useHotkeys('ctrl+s', (e) => {
  e.preventDefault();
  handleSave();
});
```

**Comment by Seanmclem** [comment]
> ```js
> e.preventDefault();
> ```

Thanks, but that doesn't change anything. The inside of the function is never hit. It never runs. I tried:

```javascript
  useHotkeys('ctrl+s', (e) => {
    debugger;;
    e.preventDefault();
    handleSave()
  });
  useHotkeys('cmd+s', (e) => {
    debugger;;
    e.preventDefault();
    handleSave()
  });
  useHotkeys('command+s', (e) => {
    debugger;;
    e.preventDefault();
    handleSave()
  });
  useHotkeys('kVK_Command+s', (e) => {
    debugger;;
    e.preventDefault();
    handleSave()
  });
```
