### ISSUE TITLE
Allow in some cases to useHotkeys to work if the event target is contentEditable

### ISSUE THREAD

**Issue by SabagRonen** [JohannesKlauss/react-hotkeys-hook#533]
I have scenario similar to the following
`<div id="container"><div id="targetId" contentEditable="true"/></div>`
if the div with targetId didn't consumed the keyboard event I think it's legit to let the div with container id to consume this event
After release 3.3.0 we can't use it in that way.

Is it make sense to allow this behaviour?

**Comment by JohannesKlauss** [comment]
You can use the `enableOnContentEditable` option as mentioned here: https://github.com/JohannesKlauss/react-hotkeys-hook/issues/511#issuecomment-824734169
I have to update the docs for that.

**Comment by SabagRonen** [comment]
thanks!!
