### ISSUE TITLE
splitKey is not working.

### ISSUE THREAD

**Issue by ElvisUpUp** [JohannesKlauss/react-hotkeys-hook#544]
the code I write below is not working.

```js
useHotkeys(`ctrl-+`, () => {}, { splitKey: '-' });
```

The version is 3.3.1.

**Comment by JohannesKlauss** [comment]
Thanks for raising the issue. I'll have a look at it.

**Comment by JohannesKlauss** [comment]
Hey @ElvisUpUp I finally got around to check this out.

This is a bug in the underlying hotkeys-js package and there is already an issue open: https://github.com/jaywcjlove/hotkeys/issues/270
I'll leave this open as a reminder that we need to bump the version once this got fixed.

**Comment by danielcrisp** [comment]
Is it possible to workaround this by using the `which` value for `+` (187) somehow?

**Comment by Enteleform** [comment]
`splitKey` is somewhat working for me, but it's buggy.

Every time the hook is called, it adds another listener, so the command is executed an increasing number times.

e.g. after 3 renders, the callback is executed 3 times per hotkey activation.

This only occurs when using `splitKey`.

**Comment by JohannesKlauss** [comment]
Do you have a codesandbox repro for that behavior?

**Comment by JohannesKlauss** [comment]
This will be implemented in version 4, so I am closing this for now. RC of version 4 is right around the corner
