### ISSUE TITLE
Unbind when enabled is false

### ISSUE THREAD

**Issue by zbeyens** [JohannesKlauss/react-hotkeys-hook#556]
At the moment, `hotkeys.unbind` is called only on component unmount. The problem is that my component is a sidebar with keyboard navigation that never gets unmounted.

Would it make sense to unbind when `enabled` updates from `true` to `false`?

**Comment by JohannesKlauss** [comment]
Sounds logical to me, since the callback won't be called anyway. I'll add it to the package.

**Comment by JohannesKlauss** [comment]
This should actually already be the case as this test shows: https://github.com/JohannesKlauss/react-hotkeys-hook/blob/e55a5ac7a810085a7f4d29f6551a502f8c4541e4/src/index.test.tsx#L220-L230

Can you provide a codesandbox to show that it does not unbind when setting `enabled` to `false`

**Comment by zbeyens** [comment]
[This actually works](https://codesandbox.io/s/jolly-hopper-1ylm7?file=/src/App.js). My bad, I forgot that the previous effect is cleaned up before executing the next effect.

Thanks for your time!
