### ISSUE TITLE
enableOnContentEditable not documented

### ISSUE THREAD

**Issue by joepio** [JohannesKlauss/react-hotkeys-hook#567]
First off, thanks for creating / maintaining this!

I was about to create an issue about not being able to ignore `contentEditable` elements, until I found the `enableOnContentEditable` setting in the type declarations. Would be awesome if it was included in the docs!

**Comment by JohannesKlauss** [comment]
You are absolutely right, I'll include it in the docs.

**Comment by JohannesKlauss** [comment]
Documentation on that can be found here: https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/disable-hotkeys#enable-hotkeys-on-tags-leveraging-contenteditable
