### ISSUE TITLE
I can't use the key 'command'

### ISSUE THREAD

**Issue by tuanant** [JohannesKlauss/react-hotkeys-hook#613]
I have written code :

`useHotkeys('command+shift+n, command+up+1', callback)`
 
but its not working. Why??

**Comment by JohannesKlauss** [comment]
If you are using Chrome, the `command+shift+n` keystroke is reserved to open a new incognito window and can't be overridden. Chrome will always trigger its own internal function.
In Firefox this works, so you can just use that: https://codesandbox.io/s/brave-bardeen-4p4s0?file=/src/App.js

Note that the `command` key is only available on macOS.

`command+up+1` works in both browsers, but again also triggers a default browser behavior that switches through the tabs in the window, `command+up+1` focusing the first tab, `command+up+2` and so on.

**Comment by tuanant** [comment]
Thank you for this help.
I'm not sure if there is a way to override it: https://codesandbox.io/s/clever-engelbart-deyzy?file=/src/App.js

**Comment by JohannesKlauss** [comment]
Well, as I said in Chrome it is not possible to override those  keystrokes.
