### ISSUE TITLE
Multiple hotkeys as ref to a single element

### ISSUE THREAD

**Issue by balboFK** [JohannesKlauss/react-hotkeys-hook#664]
Hello everybody!

Any ideia of how to achieve a solution if I have multiple hotkeys that will be scoped to the same component? Do I still need to use refs?

Lets say that on a box, I will have the hotkeys 'arrowUp' and 'arrowDown' to move said box up and down. 
How should i pass those refs?

```ts
function MyComponent() {
  const refArrowUp = useHotkeys('ArrowUp', () => { //do something to go up }  ));
  const refArrowDown = useHotkeys('ArrowDown', () => { //do something to go down }  ));

  return (
    <div>
      <span 
        ref={?} // what ref should go here?
        tabIndex='-1'
       >
        Should only enable when focusing this element.
     </span>
   </div>
  );
}
```

Should I create something like this answer o S.O or is there a better way to do that on the library itself? 
https://stackoverflow.com/a/60270745

Thanks in advance!

**Comment by JohannesKlauss** [comment]
Hey @balboFK you should be able to use a library like https://github.com/gregberge/react-merge-refs to merge two refs together.

**Comment by balboFK** [comment]
Hello @JohannesKlauss, thanks for the reply.
I tried the way the linked answer on SO said, and it worked aswell.

```ts
 const myRef = useRef(null);

  useEffect(function() {
    hoverRef.current = myRef.current;
    dragRef.current = myRef.current;
  }, [myRef.current]);
```

It's a bit hacky I would say but it saves me from adding another package to the project for now.
Thanks anyway for your time to search for that library I will keep it in mind for the future!

**Comment by btjacker** [comment]
no need useEffect, just:
 
```
  const ref1 = useHotkeys("ArrowRight", () => a.nextSelect("RIGHT"));
  const ref2 = useHotkeys("ArrowLeft", () => a.nextSelect("LEFT"));

    <div
      ref={(el) => {
        ref1.current = el;
        ref2.current = el;
      }}
      tabIndex={0}
      ></div>
```
