### ISSUE TITLE
Default value of keyup and keydown in the documentation

### ISSUE THREAD

**Issue by rosalie-liu** [JohannesKlauss/react-hotkeys-hook#672]
Hi! I just noticed a small typo in the doc: https://react-hotkeys-hook.vercel.app/docs/api/use-hotkeys
![image](https://user-images.githubusercontent.com/52677246/149599136-93cb60c0-b52f-4902-a156-91e1a5c370db.png)

It seems like `keydown` is default to `true` and `keyup` is `undefined`. Thanks!
https://github.com/JohannesKlauss/react-hotkeys-hook/blob/master/src/useHotkeys.ts#L28

**Comment by JohannesKlauss** [comment]
@rosalie-liu Thanks for raising that issue,
would you mind creating a PR to fix the typo in the docs?

**Comment by rosalie-liu** [comment]
Sorry for the delay, I created a [PR](https://github.com/JohannesKlauss/react-hotkeys-hook/pull/685) to fix the typo. Thanks!

**Comment by JohannesKlauss** [comment]
Thank you, merged it.
