### ISSUE TITLE
Disable browser default Hot keys

### ISSUE THREAD

**Issue by laiba18** [JohannesKlauss/react-hotkeys-hook#686]
How to disable default browsing hot keys .Override with our react app hot keys

**Comment by JohannesKlauss** [comment]
You can use something like this:

```js
useHotkeys('ctrl+s', e => {
  e.preventDefault()

  // Your callback
})
```

**Comment by laiba18** [comment]
Thankyou for reply one more question is:
1) If one input field focus on any hotkeys then the second hotkey does not
apply. What should we do for this scenario ?
e.g suppose I have focused on an input field then click any hotkey
doesnot execute if one field is autofocus. What should we do in this
scenario?

**Comment by laiba18** [comment]
Is it possible to one same key used into multiple functionalities. (E.g Enter key used to cover multiple scenarios)

**Comment by JohannesKlauss** [comment]
This is not a support channel. This is meant to collect bugs. Please refer to the docs for your questions: 

https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/disable-hotkeys#enable-hotkeys-on-form-fields
https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/scoping-hotkeys
