### ISSUE TITLE
Text field doesn't accept hotkey characters bound to checkbox hook

### ISSUE THREAD

**Issue by gezabela** [JohannesKlauss/react-hotkeys-hook#735]
There is an issue when a hotkey is bound to a checkbox. There is also a textbox in the app. The key that is bound to the checkbox is 'f'. In this scenario I am unable to type the letter 'f' in my textbox. 

Please check the code [here](https://codepen.io/blehel/pen/WNdPmBW)

**Comment by gezabela** [comment]
We are building a page where there is search box and a table. Multiple rows can be selected using checkboxes. There are also row specific action (f for flagging, v for validating in the context of our domain). The users can navigate through the rows using the tab key, which iterates over the rows by focusing the checkbox. So there is a separate hotkey hook attached to every checkbox in every row, but this functionality doesn't allow typing "f" and "v" in the search field.

![usecase](https://user-images.githubusercontent.com/18413761/166515061-9278815a-d526-4433-a218-1f1288b64457.jpg)

**Comment by JohannesKlauss** [comment]
You can use scoping for that:
https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/scoping-hotkeys#scoping-with-non-focusable-components

With that feature you can have the `f` and `v` hotkeys only active if the user has focused a row.

**Comment by gezabela** [comment]
Yes, but that is not the issue. I don't want the whole <td> element to be focusable. The only focus is on the focusable checkbox input element and also the hotkey hook is bound to that. That part works. But for some reason then the f and v are not typeable in the input box which technically should not listen to any hotkey. The demo code in my initial post illustrates perfectly that I cannot type the letter "f" in the input box but the code doesn't imply that that will happen.

**Comment by JohannesKlauss** [comment]
Ah ok, I understand the problem. Unfortunately this is currently not possible, but will be in version 4.
Currently all hotkeys get bound to the document, which is why it blocks in all input elements on the page.

**Comment by JohannesKlauss** [comment]
I am closing this for now. The feature/bug fix is implemented in version 4, which is right around the corner
