### ISSUE TITLE
enableOnTags not working when scoping components.

### ISSUE THREAD

**Issue by jcmartinezdev** [JohannesKlauss/react-hotkeys-hook#759]
When I try to use `enableOnTags` on a scoped element the event is not fired when an input has the focus.

Here is a code sample:

```
import * as React from 'react';
import { useHotkeys } from 'react-hotkeys-hook'
import "./styles.css";

export default function App() {
  const [count, setCount] = React.useState(0);

  const ref = useHotkeys('b', () => setCount(prevCount =>
    prevCount + 1
  ), {
    enableOnTags: ['INPUT'],
    filterPreventDefault: true
  });

  return (
    <div>
      <div ref={ref} tabIndex='-1'>
        Focusing this element will enable the hotkey {count}.
        <input type="text" />
      </div>
    </div>
  );
}
```

https://codesandbox.io/s/suspicious-mestorf-fc356x?file=/src/App.js:0-513

## Expected result:
When I press the key 'b' while focused on the input box the counter increases.

## Actual result
The counter doesn't increase, so the keyboard event is not fired, and the letter 'b' renders unusable on the input field, no matter what value is assigned to `filterPreventDefault`.

Has anyone had this issue? is it a limitation of the current implementation or a bug?

Thanks

**Comment by paullexen** [comment]
I'm also running into this problem. Does anyone have a workaround for this?
