### ISSUE TITLE
How to prevent propagation in nested components

### ISSUE THREAD

**Issue by sebpowell** [JohannesKlauss/react-hotkeys-hook#764]
I have the following use case: a select dropdown, inside a modal. 

I want to be able to set things up so that if the 'escape' key is hit when the dropdown is not open, it closes the modal, but if the dropdown IS open, it only closes the dropdown (and not the modal). 

I'm testing this idea using the following, basic approach:

```JSX

const Dropdown = () => {
  useHotkeys("esc", () => (e) => {
    e.preventDefault();
    e.stopPropagation();
    console.log("Dropdown escape");
  }, {
    enableOnTags: ["INPUT"],
  });

  return (<div>Dropdown</div>)
}

const Modal = () => {
  useHotkeys("esc", () => console.log("Modal escape"), {
   enableOnTags: ["INPUT"],
  });
 
  return (<Dropdown />)
}

```

I would have thought that using preventDefault and / or stopPropagation would do the trick here, but when I try running this code, the console.log fires twice, one for each component. 

I'm probably not going about this the right away, so any help would be greatly appreciated.

**Comment by JohannesKlauss** [comment]
You have to use the ref that is return by the hook to scope the hotkey to a component:
https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/scoping-hotkeys

**Comment by sebpowell** [comment]
I completely missed this 🤦 Thank you so much for the quick response and help!

**Comment by sebpowell** [comment]
Sorry, one other question – just tried doing this, and Typescript doesn't like it – you can see the error here:

<img width="1428" alt="Screenshot 2022-06-07 at 14 10 26" src="https://user-images.githubusercontent.com/1786366/172388150-ac758fbb-17e5-4ad2-818c-33c9e19a1143.png">

Also, regardless of TS, this doesn't seem to work – hitting the 'esc' key doesn't do anything (if I remove the ref, and just use it as shown in the regular examples, it works ok). 

Any ideas where I'm going wrong?

**Comment by sebpowell** [comment]
Ah, my bad – it DOES work, it's just TS that's not happy. I suppose I could cast the type – do you think that's the best way to go about it?

**Comment by sebpowell** [comment]
Thank you!!
