### ISSUE TITLE
isKeyPressed not working when dependencies are added to a useHotKey hook

### ISSUE THREAD

**Issue by bajcmartinez** [JohannesKlauss/react-hotkeys-hook#765]
As strange as it sounds, when we utilize `useHotKey` and we pass dependencies that trigger a component re-render, then the `isHotKeyPressed` function will not recognize such a key any longer after a component re-render.

You can see the effect in the following codesandbox:

https://codesandbox.io/s/charming-visvesvaraya-zos5vk?file=/src/App.js

**Comment by JohannesKlauss** [comment]
https://user-images.githubusercontent.com/6214415/172614913-e3b17768-74a7-4101-a136-3da1447b2870.mov

Cannot reproduce that issue. In which browser does that happen?

**Comment by bajcmartinez** [comment]
That's weird, are you constantly holding shift or holding and releasing on each click?

It happens at least on chrome while holding shift the whole time, if I release shift and press it again it works again

**Comment by JohannesKlauss** [comment]
Ah, you are absolutely right, that's odd. Have to look into it. Thank you for bringing this to my attention

**Comment by JohannesKlauss** [comment]
This seems to be related to #766 and should be fixed in the `4.0.0-1` version

**Comment by bajcmartinez** [comment]
It seems to be working now, thanks!
