### ISSUE TITLE
Scoped hotkey should be executed before a global one

### ISSUE THREAD

**Issue by vojto** [JohannesKlauss/react-hotkeys-hook#781]
In App.tsx I have:

```
useHotkeys("escape", () => ...)
```

In ContextMenu.tsx:

```
const ref = useHotkeys("escape", (ev) => ...)
// ...
<div tabIndex={-1} ref={ref}>...</div>
```

If I press Escape, the handler in App gets called first, presumably because it was set up first.

**I think scoped hotkey should get called first - the global ones should come next.**

---

To give you a better idea, this is what the context menu looks like:

<img width="190" alt="CleanShot 2022-07-16 at 08 57 33@2x" src="https://user-images.githubusercontent.com/50943/179344026-411ebb01-f427-45ed-9ed8-65f78173bba5.png">

Escape key is supposed to close it, but the app has a global handler for Esc that does something else.

**Comment by adam-olema** [comment]
Same issue.  If nothing else, the scoped/inner callback should at least get a chance to stop the event from propagating.

**Comment by JohannesKlauss** [comment]
Hmh... I am not sure how we could pull this off. Keyboard events are triggered by the browser, determining the order of them introduces a lot of overhead into a modularized hook. I am also not quite sure if ordering is what you want. I guess you actually want to suppress the execution of your global callback, but you can just implement this in user land.

Create a context that holds a boolean flag to determine if a submenu is open and wrap your app around it. Set that flag to true when the context menu is visible and give that flag to your global hotkeys `enable` option.

**Comment by vojto** [comment]
Fair enough, thank you!

**Comment by CHE1RON** [comment]
If it's not too much to ask, please share your implementation, @vojto! 😉

**Comment by vojto** [comment]
> If it's not too much to ask, please share your implementation, @vojto! 😉

I think I just check for a global state about context menu being opened. I use Mobx for state management, so it's fairly easy with that.
