### ISSUE TITLE
[4.0.0-5] Arrow keys don't execute callback

### ISSUE THREAD

**Issue by lunacrafts** [JohannesKlauss/react-hotkeys-hook#796]

**Comment by JohannesKlauss** [comment]
Can you please provide more information? How are you calling the hook? Can you share a codesandbox reproduction?

**Comment by swalker326** [comment]
Here is a code sandbox with arrow keys setting count

https://codesandbox.io/s/romantic-pike-ggs3dp?file=/src/App.tsx

Here is a link to the docs showing how to setState in your callBack

https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/basic-usage#modifiers--special-keys

**Comment by lunacrafts** [comment]
I'm sorry. I was a bit in rush and I assume the title was self explanatory.

I increased version to 4.0.0-4 in @swalker326 example. It don't execute callback. Maybe is it another difference on OSX?
https://codesandbox.io/s/bitter-thunder-lpbluv?file=/src/App.tsx

I made a workaround which looks like that:
  useHotkeys(
    "*",
    (event) => {
      if (event.key === "ArrowLeft") {
        //
      }
    },
    {
      enableOnFormTags: ["input", "select", "textarea"],
    },
    [highlighted]
  );

**Comment by JohannesKlauss** [comment]
up and down currently won't work, but I agree that they should be mapped. I'll release a fix for that

**Comment by federico-terzi-anima** [comment]
Any update on this issue? :)

**Comment by lunacrafts** [comment]
> Any update on this issue? :)

I would suggest to avoid using this version of package. I had to move to [react-use-hotkeys](https://github.com/reecelucas/react-use-hotkeys) until stable version is released.

**Comment by JohannesKlauss** [comment]
I'm quite packed with tasks currently, sorry. Maybe I'll get to it during the weekend. But you are always welcome to contribute. At the end of the day, this is how open source projects live on.

**Comment by federico-terzi-anima** [comment]
Thank you for the update! I appreciate your hard work :)

**Comment by JohannesKlauss** [comment]
Fixed with Pre release version 4.0.0-6
