### ISSUE TITLE
Record Shortcuts (Map Input Event to shortcut string)

### ISSUE THREAD

**Issue by YeonV** [JohannesKlauss/react-hotkeys-hook#798]
First of all: GREAT project!!!! Thank you soo much!

Could you provide function to be used to record a shortcut?
A function to be called on an Input Field onChange, returning the shortcut string understandable by useHotkeys() i.e. 'ctrl+alt+y'

So users can map their own shortcut in frontend?

Sorry for this bad english, I hope you can still somehow understand me

Gratefully
Blade (YeonV)

**Comment by JohannesKlauss** [comment]
That sounds like a nice additional feature. I put it up on the roadmap to V4, but might land in 4.1
First I'd like to finally finish the major release.

**Comment by YeonV** [comment]
> That sounds like a nice additional feature. I put it up on the roadmap to V4, but might land in 4.1 First I'd like to finally finish the major release.

Thank you soo much for answering me <3

![image](https://user-images.githubusercontent.com/28861537/187240495-3474824d-aedb-4d12-9472-ae6898212b0b.png)

maybe you can use some of my noob code:

```js
import { useState } from 'react';
// import { useStore } from '../../store/useStore';
import { useHotkeys } from 'react-hotkeys-hook';

const Example = () => {
  const [shortcut, setShortcut] = useState('ctrl+alt+y')
  const [ctrl, setCtrl] = useState(false)
  const [alt, setAlt] = useState(false)
  const [shift, setShift] = useState(false)
  const [win, setWin] = useState(false)
  const [key, setKey] = useState('')
  const shortcuts = useStore((state) => state.example.shortcuts);

  /* store


shortcuts: [{
    shortkey: "ctrl+alt+y",
    trigger: () => alert('Boom'),
    }
  ]
 */
  // const addShortcut = useStore((state) => state.example.addShortcut);

  shortcuts.map(({shortkey, trigger}) => {    
    useHotkeys(shortkey, () => trigger(),{},[shortcuts])
  })  

return (<>
 <Stack direction={'row'} gap={2}>
        {shortcut.split('+').map((s,i) => <Button key={i} variant={(s === 'ctrl' && ctrl) || (s === 'alt' && alt) || (s === 'shift' && shift) || (s === 'cmd' && win) || (s === 'win' && win) || key ? 'contained' : 'outlined'}>{s}</Button>)}
        <Button variant='contained' onClick={()=> addShortcut(shortcut, () => alert(1))} >Save</Button>

        </Stack>

        <Input 
          onKeyDown={(e) => {
            if (e.ctrlKey) {
              setCtrl(true)
            }
            if (e.altKey) {
              setAlt(true)
            }
            if (e.shiftKey) {
              setShift(true)
            }
            if (e.metaKey) {
              setWin(true)
            }        
            if (e.code.includes('Key') && e.code.replace('Key','') && e.code.replace('Key','') !== '') {
              setKey(e.code.replace('Key',''))
            }        
            setShortcut([e.ctrlKey ? 'ctrl' : null, e.altKey ? 'alt' : null, e.shiftKey ? 'shift' : null, e.metaKey ? 'win' : null, e.code.includes('Key') && e.code.replace('Key','')].filter(n => n).join('+')) 
          }} 
          onKeyUp={(e) => {
            if (e.ctrlKey === false) {
              setCtrl(false)  
            }
            if (e.altKey === false) {
              setAlt(false)
            }
            if (e.shiftKey === false) {
              setShift(false)
            }
            if (e.metaKey === false) {
              setWin(false)
              setKey('')
            }
            if (e.code.includes('Key')) {
              setKey('')
            }    
            console.log(e)        
          }} 
        />
</>
)
```

everything run super nice, but i have one question:
when trying to add a shortcut from the frontend, i get an error regarding that the hooks changed from previous render.

Do you have a tip, how i could solve this issue?
![image](https://user-images.githubusercontent.com/28861537/187243070-167ad213-b4f8-452c-8ded-8135cb1a52cd.png)

thank you very much

**Comment by YeonV** [comment]
Yooo @JohannesKlauss :)
https://yeonv.github.io/io/
![image](https://user-images.githubusercontent.com/28861537/187324544-8457e395-e6ec-43b3-b1f5-ccfd2dbdff88.png)

works like a charm!

**Comment by JohannesKlauss** [comment]
This feature landed in https://github.com/JohannesKlauss/react-hotkeys-hook/releases/tag/v4.2.0
