### ISSUE TITLE
Latest version on NPM?

### ISSUE THREAD

**Issue by chiefGui** [JohannesKlauss/react-hotkeys-hook#80]
Hey!

I'm willing to use your package, but I'm seeing some `console.log` messages that seems to be already patched yet not available on NPM.

Would you mind to publish a new version with the updates, @JohannesKlauss?

**Comment by chiefGui** [comment]
https://github.com/JohannesKlauss/react-hotkeys-hook/tree/hotfix/remove-console-logs

**Comment by JohannesKlauss** [comment]
Hi @chiefGui
Yes, I totally forgot to do that. Sorry.

**Comment by JohannesKlauss** [comment]
@chiefGui I published a new version with the removed console.logs

**Comment by chiefGui** [comment]
Thanks!
