### ISSUE TITLE
Question Mark (SHIFT+?) Not Supported

### ISSUE THREAD

**Issue by johnsoncode** [JohannesKlauss/react-hotkeys-hook#804]
It appears that the question mark is not supported due to the callback not being called and I don't see the corresponding mapping in the hotkeys js library as well.

My work around for now, though not ideal as I have many other shortcut hooks registering other hotkeys. This will be invoked anytime a key is pressed and may run into performance issues later.
```js
useHotkeys('*', (e) => {
    if (e.shiftKey && e.key === '?') {
        ...
    }
});
```

**Comment by FranRioLorda** [comment]
Hi. I think that "<" and ">" had a similar issue and are not supported neither
