### ISSUE TITLE
Hotkey not working when input is focused inside iframe

### ISSUE THREAD

**Issue by pbshgthm** [JohannesKlauss/react-hotkeys-hook#809]
Let's say a react component `Foo` is rendered inside an iframe using [react-frame-component](https://github.com/ryanseddon/react-frame-component). Now `Foo` has a `useHotkeys` hook. Everything works as expected. `Foo` also has an input element. When the input element comes into focus, `useHotkeys` doesn't work anymore. Even if the input gets out of focus, the `useHotkeys` doesn't work. As long as no input/contentEditable div is ever in focus, no issues. If it gets in focus even once, `useHotkeys` stops working, until a page refresh. Adding `{ enableOnTags: ["INPUT"] }` also didn't help fix it. Where should I look at?

Since it's a little weird setup (I'm working on an extension using React), I'm not adding an issue-reproducible repo code. Based on what exactly would be useful for troubleshooting, I can create an issue-reproducible code snippet.

Thanks in advance!

**Comment by MaxAlex666** [comment]
I think there is no dependency on react-frame-component here, in the usual form I have been observing the same behavior for a long time, I have not yet found a solution.

**Comment by gontovnik** [comment]
Have a similar issue – whenever I click within iframe and focus changes to the iframe, hotkeys do not work.

**Comment by JohannesKlauss** [comment]
This should be fixed with 4.3.0
If the issue persists please let me know and create a reproducible sandbox

**Comment by edikurniawan-dev** [comment]
sorry in my apps it's still doesn't work

**Comment by JohannesKlauss** [comment]
@edikurniawan-dev create a reproducible and open a new issue
