### ISSUE TITLE
Is handler.key outdated in v4?

### ISSUE THREAD

**Issue by gummigun** [JohannesKlauss/react-hotkeys-hook#838]
I was trying out v4 and can't seem to be able a "key" attribute from the handler object like the docs show here:
https://react-hotkeys-hook.vercel.app/docs/api/use-hotkeys

It does have a "keys" attribute that's an array. Are the docs just in need of update or am I missing something?

**Comment by JohannesKlauss** [comment]
Ah yes, that's a typo. It should be `keys`. I will update the documentation
