### ISSUE TITLE
useHotKeys inside Iframe

### ISSUE THREAD

**Issue by spavlukevich** [JohannesKlauss/react-hotkeys-hook#843]
Hi there!

**version**: react-hotkeys-hook@4.0.2

I'm trying to use ```useHotKeys``` inside ```react-frame-component``` Iframe, but when i'm focusing on iframe and pressing some hotkeys, events doesn't work, nothing happens, example: 

```
import React, { memo, useRef, useEffect, useCallback } from 'react'

import Frame, { FrameContextConsumer, useFrame } from 'react-frame-component'

import {useHotkeys} from 'react-hotkeys-hook'

const InnerComponent = () => {

	const { document, window } = useFrame();

	useHotkeys('s', (event) => {
		console.log('s pressed');
	})

	return null;
};

const Editor = () => {
	return (
		<>
		 	<Frame>
				<InnerComponent/>
			</Frame>
		</>
	)
}
export default memo(Editor)
```

what i'm doing wrong, or maybe i need to pass some arguments to ```useHotkeys``` function? 

thanks!

**Comment by spavlukevich** [comment]
what's wrong with my question? why you are ingoring this?

**Comment by JohannesKlauss** [comment]
Because I have very little time right now since I am fully involved in my daytime job, sorry.
If you can send me a link to a reproducible codesandbox I can fix it faster

**Comment by mbrevda** [comment]
Had similar issues with other libs when using React Portals (like react-helmet and many css-in-js libs that want to access `<head>` and all assume that `<head>` is located at `document.getElementsByTagName('head')[0]`).

It boils down to listening on the wrong [`document`](https://github.com/JohannesKlauss/react-hotkeys-hook/blob/main/src/useHotkeys.ts#L56) (i.e. the parent docuemtn, where react lives, instead of listening on the iframe's `document`) . It's likely that being able to pass `document` to the hook will resolve the issue

**Comment by mbrevda** [comment]
I see this was already mentioned [here](https://github.com/JohannesKlauss/react-hotkeys-hook/issues/405)

**Comment by JohannesKlauss** [comment]
Thanks for the pointer! Will try that out

**Comment by spavlukevich** [comment]
> Because I have very little time right now since I am fully involved in my daytime job, sorry. If you can send me a link to a reproducible codesandbox I can fix it faster

@JohannesKlauss sure

codesandbox: https://codesandbox.io/s/epic-forest-7rbkhw

steps to reproduce: 

1) focus on body and press `s` key, you'll see `s pressed` in console
2) focus on iframe and and press `s` key, you'll see nothing on console

**Comment by JohannesKlauss** [comment]
Starting with 4.3.0 you can set a different document to bind to in the useHotkey hook like so:

```js
import FrameComponent from 'react-frame-component'

const InsideFrameComponent = () => {
  const { document } = useFrame()

  useHotkeys("s", () => console.log("I am triggered inside an iframe"), { document })

  return <div>....</div>
}

function App() {
  return (
    <FrameComponent>
      <InsideFrameComponent/>
    </FrameComponent>
  )
}
```

Thanks to @mbrevda for the pointer to the solution!
