### ISSUE TITLE
Difference in behavior v3 and v4 when using a comination with shift key

### ISSUE THREAD

**Issue by KimPeeters** [JohannesKlauss/react-hotkeys-hook#848]
Hi,

Prior to version 4 you if you wanted the hotkey for "shift+3" for example, you could use that combination. In the v4 version, you need to use "shift+#" (for my keyboard layout at least). I assume this is because of the removal of hotkeys.js and implementing your own solution. 

I think the way it was prior to v4 was better because in my case i want for users to be able to use shift 1 through 5 for specific tasks. But the way i have to specify that now, it only works now if they use the same keyboard layout.

Greetings.

**Comment by psychedelicious** [comment]
Have just run into this with a user who has a QWERTZ keyboard.

To send `[` and `]` on their keyboard layout, they use right alt + 8 (`[`) or 9 (`]`). This isn't caught by the hook.

**Comment by joshkel** [comment]
@KimPeeters, react-hotkeys-hook can match on [code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) (lowercased, with the leading `Key` removed) as well as key, so matching `shift+digit1` through `shift+digit5` should work.

@psychedelicious, the right alt (AltGr) should be reported as [Ctrl + Alt](https://stackoverflow.com/a/18570096/25507), so I think you can match on `['[', ']', 'ctrl+alt+[', 'ctrl+alt+]']`. I don't have a QWERTZ keyboard to test (and it might be nice to have an option that doesn't require manually handling alternate keyboard layouts like this - although I'm not sure of a good way to do that).

**Comment by KimPeeters** [comment]
@joshkel Great! I'll start using codes from now on. Thanks for the feedback!

**Comment by pauloendoh** [comment]
I was using shift+2 and had to change to shift+digit2 , it would be nice to have this clear in the doc.

**Comment by JohannesKlauss** [comment]
Should be fixed in 4.0.5
