### ISSUE TITLE
Memoize setters from context

### ISSUE THREAD

**Issue by ptya** [JohannesKlauss/react-hotkeys-hook#853]
Hi,
I'm now trying to use the scope based disabling/enabling actions and I noticed that by using `useHotkeysContext` the underlying functions are simple arrow functions which makes every component using that hook rerender anytime the provider rerenders. Wrapping them into `useCallback`s would solve this issue.

I have a recommendation as well on this.
If you were to separate `state` and `function` context values, each in its own context, then you could eventually make it more resistant to rerenders.

**Comment by JohannesKlauss** [comment]
Fixed in 4.0.8
