### ISSUE TITLE
Disabling all scopes turns everything on

### ISSUE THREAD

**Issue by ptya** [JohannesKlauss/react-hotkeys-hook#854]
Hi,
Just as I wrote my other issue I noticed a potential bug in the code. Now when you disable a scope, and there are no more enabled scopes after filtering, instead of turning everything off, the codes turns everything back on again. I don't think that is the intended usecase here.

**Comment by JohannesKlauss** [comment]
Thank you for reporting the issue.

**Comment by JohannesKlauss** [comment]
This is actually intended behavior. If you disable all specific scopes the wildcard scope will be active which means all scopes are active. Although thinking about it this seems very counter intuitive and I might change that in a 4.1 version.

Right now you can workaround by initially setting a scope `none`

**Comment by colinricardo** [comment]
@JohannesKlauss is there a recommended way of disabling all scopes? looping over the active scopes and calling disableScope doesn't seem to work
