### ISSUE TITLE
[BUG] no listeners cleanup in v4

### ISSUE THREAD

**Issue by suren-atoyan** [JohannesKlauss/react-hotkeys-hook#857]
https://user-images.githubusercontent.com/13118722/205069820-014baac7-d2af-45e7-88b2-76a10acccace.mov

@JohannesKlauss seems you do not clean up previous listeners; this leads to bad issues.

**Comment by joshkel** [comment]
@suren-atoyan , is that test case available anywhere (e.g., on codesandbox.io)? 

From a brief look at the `useHotkeys` implementation, I'm not sure that its use of `ref.current` to both add the event handler and remove it is correct:

https://github.com/JohannesKlauss/react-hotkeys-hook/blob/66fbc876f9691a43233bd52b7d7149c45fb54ace/src/useHotkeys.ts#L104-L117

(See [here](https://github.com/facebook/react/blob/f0534ae94a439dc7ac782b973792da59dbde7a7f/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L502) in the eslint-plugin-react-hooks plugin.) I'm not sure if this is the cause of your problem, though.

**Comment by JohannesKlauss** [comment]
I am not sure what your issue is. The coding example works just as expected. It is interacting with a squared count of a useMemo to present the usage of changing dependencies that interact with each other. Read the example more carfully.
