### ISSUE TITLE
Key documentation

### ISSUE THREAD

**Issue by baoskee** [JohannesKlauss/react-hotkeys-hook#859]
Is there a list of the key strings and what they represent? I have no idea what key string is for ArrowDown and ArrowUp. Also the doc is stale for replacing `command` with `meta`.

**Comment by JohannesKlauss** [comment]
You can use `down` or `arrowdown` or `ArrowDown`. https://codesandbox.io/s/competent-shamir-tseirb?file=/src/App.tsx

I will update the docs for the stale `command` and `cmd` usage

**Comment by baoskee** [comment]
Thanks!
