### ISSUE TITLE
ctrl combo seems to be broken after updating to 4.0.6

### ISSUE THREAD

**Issue by naquarius** [JohannesKlauss/react-hotkeys-hook#869]
hello! I'm upgrading from v3.4.7 to 4.0.6 (there was previously an issue with build with 4.0.3)
before the upgrade we were using `ctrl+shift+k` to open a dialog, after the update the key combo no longer triggers.

we've tried a few combinations like `ctrl+k` `shift+k` `alt+shift+k` and the only one that's broken is `ctrl+k`. is anyone else running into the same issue? 

MAC OS VENTURA 13.0.1 with magic keyboard with numeric pad

**Comment by JohannesKlauss** [comment]
`Ctrl` has been replaced by `meta` in version 4

**Comment by naquarius** [comment]
can you please update the read me or documentation for this? the example still has ctrl which is a bit confusing
