### ISSUE TITLE
"ctrl" option completely missing on macOS

### ISSUE THREAD

**Issue by firatciftci** [JohannesKlauss/react-hotkeys-hook#870]
From what I understand, the update from v3 to v4 completely gets rid of the distinction between `"command"` and `"ctrl"` on macOS. While I sort of understand how this makes sense on Windows (i.e., `"meta"` is `"ctrl"`, and the Windows key should not be remapped by a website), the change severely limits how macOS functions.

For example, I have a web app set up where I had been using `"ctrl+shift+c"` to open up a menu, but switching this to `"meta+shift+c"` simply does not work, as `"command+shift+c"` toggles Chrome's CSS inspect element mode. `"command"` on macOS is heavily utilized by system and browser functionality, so taking away `"ctrl"` altogether is a significant feature loss for this package.

Could there be an update to bring back `"meta"` and `"ctrl"` separately? It could be mapped so that the two are interchangeable on Windows, but on macOS, `"meta"` points to `"command"`, and `"ctrl"` to `"ctrl"`.

**Comment by JohannesKlauss** [comment]
You can just use the `preventDefault: false` option to suppress browser default action for hotkeys:
https://codesandbox.io/s/stoic-carlos-xym0dq
