### ISSUE TITLE
The command key does not trigger properly on macOS

### ISSUE THREAD

**Issue by Baoyuantop** [JohannesKlauss/react-hotkeys-hook#871]
- macOS 13.0
- Chrome 107.0.5304.110

Here is a demo:
https://stackblitz.com/edit/react-ts-zo3pgh?file=App.tsx

**Comment by iamytg** [comment]
Try using "Meta" instead of "command".

**Comment by Baoyuantop** [comment]
> Try using "Meta" instead of "command".

Thanks, it works for me.
