### ISSUE TITLE
Enable triggering handlers via numpad keys

### ISSUE THREAD

**Issue by vitauto** [JohannesKlauss/react-hotkeys-hook#872]
Currently only keyboard events of number keys with the `code: Digit*` are being triggered on key press.
I enabled the triggering of the those handlers for keyboard event with `code: Numpad*` after removing  the number entries in `mappedKeys` map in file `parseHotkeys.ts`.
Can you make it as the library sefault please :)

**Comment by JohannesKlauss** [comment]
Hmh... Wer might need a reverse mapping for that, so that `digits 0..9` map to `digit0...digit9` and `numpad0..numpad9`.
I'll check on that

**Comment by JohannesKlauss** [comment]
Fixed in 4.1.0
