### ISSUE TITLE
React hotkeys does not work in nextjs above version 4.0.5

### ISSUE THREAD

**Issue by Vaasu-Dhand** [JohannesKlauss/react-hotkeys-hook#877]
I have a nextjs project that was running react-hotkeys-hook version `4.0.5`. I was running into a separate issue that's already opened (clicking browser autofill causes toLocalLowerCase()). I upgraded my package version to 4.0.8 and it completely stopped working. 
It looks like 4.0.5 was the last version that worked for me.

**Comment by JohannesKlauss** [comment]
Works just fine for me: https://stackblitz.com/edit/nextjs-e6toqq?file=pages%2Findex.js
Can you elaborate on what is not working?
