### ISSUE TITLE
enableOnFormTags still not working v4.3.0

### ISSUE THREAD

**Issue by edikurniawan-dev** [JohannesKlauss/react-hotkeys-hook#888]
`useHotkeys(
        'esc',
        () => setShowModal(false),
        {
            enableOnFormTags: 'input' | 'textarea' | 'select' | 'INPUT' | 'TEXTAREA' | 'SELECT',
        },
    );`
    
I've used `enableOnFormTags` but it still doesn't work when input is focused

**Comment by JohannesKlauss** [comment]
Please provide a reproducible codesandbox as instructed by the bug report template
