### ISSUE TITLE
[BUG] ALT + TAB Never fires keyup event for ALT so ALT is then treated as being held down.

### ISSUE THREAD

**Issue by Dastari** [JohannesKlauss/react-hotkeys-hook#890]
**Describe the bug**
When you Alt+Tab out of the window and back in again, the Alt key is still considered as being held down as the browser never fires the key up event.

**To Reproduce**
1. Go to the Sandbox Below
2. Click on Button to check if Alt is down (Should be No)
3. Alt+Tab out of the Window then back into it
4. Click on Button to check if Alt is down (Should be Yes)

[https://codesandbox.io/s/funny-christian-3tqoro?file=/src/App.js](https://codesandbox.io/s/funny-christian-3tqoro?file=/src/App.js)

**Expected behavior**
When browser window returns to focus only keys that are actually held down should act as if they are being held down.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge (Chromium)
 - Version: 108.0.1462.54 (Official build) (64-bit)

**Additional context**
I haven't done a PR yet however I believe the fix is to add an additional handler **"window.addEventListener('blur', keyUpHandler)** wherever the **document.addEventListener('keuUp', keyUpHandler)** is called.

**Comment by JohannesKlauss** [comment]
Thanks for raising that issue. I'll have a look into it

**Comment by JohannesKlauss** [comment]
Fixed in 4.3.1
