### ISSUE TITLE
[BUG] "CTRL/Control+C" call a function when you set only "C" in useHotkeys

### ISSUE THREAD

**Issue by pawelmidur** [JohannesKlauss/react-hotkeys-hook#903]
**Describe the bug**
When you set useHotkeys('c'... function is call when press ctrl/control+c or command+c, but only one time if you don't keyup mod key 

**To Reproduce**
1. set only one key like 'c'
2. press CTRL/Control+C and 'count' will increase

Please try and add a codesandbox or stackblitz to reproduce the bug:
https://codesandbox.io/s/determined-silence-830bc4?file=/src/App.js

**Expected behavior**
Press CTRL/Control+C should not cause a function in useHotkeys

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version 108.0.5359.98 (Official Build) (arm64)

**Comment by animify** [comment]
@JohannesKlauss is this an easy fix? Also very weird now that I've half way re-implemented shortcuts for https://amie.so/ - would be perfect to get this solved too ❤️

**Comment by JohannesKlauss** [comment]
I am always a bit tight on free time. Feel free to take a crack at this

**Comment by JohannesKlauss** [comment]
Fixed in 4.3.3
