### ISSUE TITLE
[BUG] After update to v4, repeated keys are no longer working

### ISSUE THREAD

**Issue by iraklid** [JohannesKlauss/react-hotkeys-hook#913]
On v3 version of the library, pressing key would constantly call callback, giving possibility to make repeated keys. With v4 update that functionality is no longer available, any options how this can be implemented in current library version?
 Or maybe I am missing some option in v4. Thanks!

**Comment by kwhitaker** [comment]
We're also seeing this change, and would appreciate some guidance on how to restore the behavior, if possible.

**Comment by corysimmons** [comment]
Rolling back to `3.4.7` (`yarn add react-hotkeys-hook@3.4.7`) until this is fixed.

**Comment by JohannesKlauss** [comment]
Yes, this is true. I intentionally removed this, since a lot of users were annoyed by that behavior. I'll add it back as an optional feature.
