### ISSUE TITLE
`type Keys` should actually be all the available keys

### ISSUE THREAD

**Issue by corysimmons** [JohannesKlauss/react-hotkeys-hook#922]
It's currently just `export declare type Keys = string | string[];`

It'd be really nice if I got hints for stuff like `backspace`, etc... I hate having to look up what key strings actually work.

**Comment by corysimmons** [comment]
For posterity, you can do this right now 🎉 

```tsx
import { Key } from 'ts-key-enum'

useHotkeys(Key.Backspace, () => {
  console.log(`delete`)
})
```

**Comment by JohannesKlauss** [comment]
As you said, you can implement this in user land. I'll add a section in the documentation referencing that library.
