### ISSUE TITLE
[BUG] "meta" key not working 

### ISSUE THREAD

**Issue by salmonzhg** [JohannesKlauss/react-hotkeys-hook#935]
"meta" key no longer working on windows since version 4.3.4 released.

**Comment by JohannesKlauss** [comment]
Please use the given bug template. Which browser are you using?

**Comment by JohannesKlauss** [comment]
I only have access to windows via Parallels Desktop and I'm not sure how great this is, because it also does mapping from my mac keyboard layout to the windows layout, but I think it is fixed.

Could you please install version 4.3.6-4 and check if the issue still persists?

**Comment by JohannesKlauss** [comment]
Fixed in 4.3.6
