### ISSUE TITLE
[BUG] `alt+d` not working

### ISSUE THREAD

**Issue by filipw01** [JohannesKlauss/react-hotkeys-hook#950]
**Describe the bug**
`useHotkeys('alt+d', callback)` is not firing callback (at least on mac)

**To Reproduce**
use useHotkeys with `alt+d`

Please try and add a codesandbox or stackblitz to reproduce the bug:
I added other keys with alt+a and shift+d to show that they are working
https://stackblitz.com/edit/react-f5lrq8?file=src/App.js

**Expected behavior**
callback should be fired

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1 (arm based mac)
 - Browser Chromium based (arc 0.89.2)
 - Version 110.0.5481.90

**Comment by JohannesKlauss** [comment]
I checked it out (mac 12 on Chrome) works fine for me.

**Comment by filipw01** [comment]
I'm on mac 13.2.1, standard QWERTY English keyboard. I see they `keydown` event is not triggered at all with this combination and I have no idea why

Karabiner event viewer sees it working, but I get a consistent lack of browser event in the browser

**Comment by filipw01** [comment]
Interesting, confirmed on another Mac that it's working

**Comment by filipw01** [comment]
Will look for a coworker next week with a similar macbook to check it out there too

**Comment by danieladarve** [comment]
mac 13.2
chrome 109.0.5414.119 => not working
safari Version 16.3 => not working

**Comment by JohannesKlauss** [comment]
This is weird.
Can you please tell me what the console output is on this [codesandbox](https://codesandbox.io/s/react-hotkeys-template-bzvk53?file=/src/App.js), when you are pressing alt+d?

**Comment by filipw01** [comment]
For me there's nothing in the console for alt+d, but that's the only combination that I found not working.
It works for one person on intel mac 13.2
and one person arm mac 13.1 as well as for one coworker on arm 13.2.1 (like I am)

My conclusion is that probably something is "stealing" option + d combination globally in my OS I checked Arc, Chrome, Firefox and Safari and none of them work. When I checked Karabiner EventViewer it's there so there must be something in between

**Comment by filipw01** [comment]
When it comes to me the issue can be closed. I don't know about @danieladarve case

**Comment by JohannesKlauss** [comment]
If you listened to the wildcard and alt+d doesn't log something, then it definitely gets blocked somewhere.

**Comment by danieladarve** [comment]
nothing comes up in console for me

**Comment by filipw01** [comment]
I found my issue. It was https://jumpshare.com/ app hijacking the `option + d` combo. It's resolved for me

**Comment by JohannesKlauss** [comment]
@danieladarve Looks fine for me. The correct events are getting triggered, so the callback should get executed.

**Comment by danieladarve** [comment]
> @danieladarve Looks fine for me. The correct events are getting triggered, so the callback should get executed.

yea looks like there is something and not related to this package
