### ISSUE TITLE
[BUG] unnecessary non-dev dependencies: eslint, eslint-plugin-react

### ISSUE THREAD

**Issue by metrip** [JohannesKlauss/react-hotkeys-hook#956]
**Describe the bug**
`package.json` has modules `eslint` and `eslint-plugin-react` in `dependencies` instead of `devDependencies`.

**To Reproduce**
N/A

**Expected behavior**
No extra modules installed

**Screenshots**
N/A

**Desktop (please complete the following information):**
all

**Additional context**
N/A

**Comment by JohannesKlauss** [comment]
Thank you for reporting this. I'll publish a fix for that

**Comment by JohannesKlauss** [comment]
Fixed in 4.3.7
