### ISSUE TITLE
[BUG] Event keyup doesn't trigger for 'ctrl'

### ISSUE THREAD

**Issue by ShekoMaxim** [JohannesKlauss/react-hotkeys-hook#959]
**Describe the bug**
Event `keyup` doesn't trigger for 'ctrl', only `keydown`

**To Reproduce**
`useHotkeys('ctrl', (event) => {console.log(event.type)}, {keydown: true, keyup: true});`

Please try and add a codesandbox or stackblitz to reproduce the bug:
[<-- Link to reproducable -->](https://codesandbox.io/s/react-hotkeys-hook-4svtbl?file=/src/App.js)

**Expected behavior**
Event `keyup` also should trigger for 'ctrl'

**Comment by JohannesKlauss** [comment]
Fixed in 4.3.7
