### ISSUE TITLE
[BUG] Stored hotkey is not cleared properly when isEnabled is dynamically switched

### ISSUE THREAD

**Issue by ptya** [JohannesKlauss/react-hotkeys-hook#974]
**Describe the bug**
If the key event listener is using the `isEnabled` option that is toggled by the callback the hotkey is used for, it will not clear properly, as the `isEnabled` option could reach the hook sooner than the `keyup` event happens.

This would be solved if in the effect in the return function, we clear the stored hotkeys along the event listeners.

**To Reproduce**

1. enable the hook's `isEnabled` option dynamically
2. pass in a callback that turns off the value being passed to `isEnabled`
3. press the hotkey required for the hook to run (depending on your codebase and machine, you might need to keep it pressed)
4. release the hotkey
5. do something that turns the hook back on
6. press any other key
7. callback is called regardless of key used

It is most probably because of this:

1. `isEnabled` turns on
2. (react-hotkeys-hook) hotkey event listener registers itself
3. hotkey keydown event triggers
4. (react-hotkeys-hook) saves the hotkey key to its reference and calls the handler that got passed in
5. our handler turns off the variable responsible for `isEnabled`
6. RACE CONDITION! does keyup event happens first, or the boolean switch for state run first?
7. (most probable winner is boolean switch) so `isEnabled` turns false, and react-hotkeys-hook receives the update
8. (react-hotkeys-hook) notices the new props so it removes every listener and does not register new ones as it is disabled
9. `isEnabled` turns on again
10. (react-hotkeys-hook) hotkey event listener registers itself again
11. ANY key keydown event triggers
12. (react-hotkeys-hook) receives a keydown event, and checks that if it happens for the same key
13. (react-hotkeys-hook) since it is not the hotkey it moves on and checks if the hotkey we're looking for is stored in its internal ref
14. (react-hotkeys-hook) as the hotkey is still in the ref, it thinks we're good to go and calls the handler that it is not supposed to call

**Expected behavior**
Only run the callback when the keys required are indeed pressed

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: any
 - Browser [e.g. chrome, safari]: any
 - Version [e.g. 22]: any

**Comment by JohannesKlauss** [comment]
Hi @ptya, thank you for that report. Unfortunately I cannot reproduce that bug. I tried it with this sandbox. Following your steps to reproduce, the behavior seems correct to me:

https://codesandbox.io/s/boring-pine-cj9hyq?file=/src/App.js

Could you please edit the codesandbox, so that the problem is reproducible?

**Comment by ptya** [comment]
hi @JohannesKlauss , thanks for the quick sandbox project. I will need to check it against our code and see, please give me a couple of days :)

**Comment by ptya** [comment]
Unfortunately I haven't got time to dig deeper here, so expecting that this is due to our own codebase, I am closing this issue, and I'll create a new one if required with more information. Thank you.
