### ISSUE TITLE
keys set uppercase and lowercase?

### ISSUE THREAD

**Issue by bbaduser** [JohannesKlauss/react-hotkeys-hook#993]
i want to set hotkeys  with uppercase and lowercase,but it dont fire
<img width="299" alt="image" src="https://user-images.githubusercontent.com/120174736/227546426-7892a24e-9006-4bf3-9470-12a71b37c8e5.png">

**Comment by joaom00** [comment]
To listen for upper case letter you should use `shift+v`.
